- scrapers/MediaPassion.cpp
Media Passion scraper has changed its API URL. There's a 301 redirect on old url, but QNetworkAccessManager doesn't follow it.
Thanks.
> Change MediaPassion URL

- MediaElch.pro
These are not necessary; I can build without them.
> do not require zen and mediainfo for building on mac

- mediaCenterPlugins/XbmcXml.cpp
Right now MediaElch can already read and save data in a subdirectory (eg. using "metadata/poster.jpg") but only if the path exists before saving.
Theese changes remove this limitation.
> Let save functions to mkdir in path

- scrapers/UniversalMusicScraper.cpp
- trailerProviders/HdTrailers.cpp
- hd-trailers changed their markup slightly and now requires an extra space in the regexp that parses out trailer results
- musicbrainz now requires a user-agent for all requests (per their throttling guidelines), which was breaking results for the universal music scraper
- musicbrainz also redirects to the non www url for all requests, so rewrote those to skip the unnecessary redirects
> Scraper fixes

- scrapers/TheTvDb.cpp
- scrapers/TheTvDb.h
- TheTvDb mirrors.xml is deprecated: remove it
- https://www.thetvdb.com/wiki/index.php/API:mirrors.xml
This PR is similar to 362 but uses `QStringLiteral` for member initializers.
Tested on:
- Linux Mint 18.3 with Qt 5.9.0 and GCC
> Remove deprecated TheTvDB mirrors API

- scripts/format.sh
Fixes the clang-format script for macOS.
macOS' `find` does not support `\|` in the RegEx pattern.
> Fix format script on MacOS

- data/MovieProxyModel.cpp
- fix undefined behavior reading a uninitialized bool
- this bug was responsible for never showing movies on mac
and randomly on linux
The bug came with 2bd3a741f6fcabcb44aff57da00f7427cd046de4 (Merge master). The branch my changes regarding member-initialization was based on didn't include the duplicate finder and therefore didn't initialize `m_filterDuplicates{false}`. This must have been forgotten while merging.
This led  to undefined behavior. The result was that:
- on linux every ~6 time I started MediaElch, no movies appeared
- on Mac no movies appeared at all (most of the time, like ~98%)
First I thought that my `apply clang-format` PR was the issue. It took me a while that the issue was the merge. But everything should work now :smile:
> Fix undefined behavior

- data/Storage.cpp
- using braced initialization for a struct fails
An error occurred with clang-6. It didn't occur with the clang version installed on my Mac.
> Fix clang build

- MediaElch.pro
- main.cpp
- xbmc/XbmcSync.cpp
This PR makes this project require Qt version 5.5 and above in the `.pro` file.
It also removes some checks (Qt >= 5.1.0). Not all checks are removed to avoid merge conflicts with other pull requests.
> Require Qt >= 5.5

- imageProviders/FanartTv.cpp
- imageProviders/FanartTvMusic.cpp
- imageProviders/FanartTvMusicArtists.cpp
- imageProviders/MediaPassionImages.cpp
- imageProviders/TMDbImages.cpp
- scrapers/IMDB.cpp
- scrapers/UniversalMusicScraper.cpp
- scrapers/UniversalMusicScraper.h
- xbmc/XbmcSync.cpp
- xbmc/XbmcSync.h
- use QtJsonDocument instead of QtScript parsing
- reason: QtScript is deprecated
- not all occurrences of QtScript are removed, yet
> Remove usage of QtScript in ImageProviders and some scrapers

- export/ExportDialog.cpp
Since the data is exported in a HTML file, all the strings that may contain HTML entities (`"`, `<`, `>`, `&`) should be escaped so that they don't break the syntax of the HTML file.
> Escape HTML entities in exported strings

- data/Storage.h
- globals/ImageDialog.cpp
- main/MainWindow.cpp
- music/Album.cpp
- music/Album.h
- music/Artist.cpp
- music/Artist.h
- music/MusicFileSearcher.cpp
- music/MusicFileSearcher.h
- music/MusicModel.cpp
- smallWidgets/SlidingStackedWidget.cpp
- smallWidgets/SlidingStackedWidget.h
- remove doubled if condition
- remove doubled condition body
- add "explicit" keyword
- move "default" keyword to header in some places
- Storage.cpp: initialize pointers to nullptr in constructors
*using:* `cppcheck --enable=all -iquazip -j4 . 2> cppcheck.txt`
> Fix various cppcheck errors

- desktop/MediaElch.desktop
- "Encoding" is deprecated
- "Version" refers to the file format's version
- "Video" in "Categories" requires "AudioVideo" to be present
> Fix linux .desktop file

- doc/advancedsettings.xml
- settings/AdvancedSettings.cpp
- settings/AdvancedSettings.h
*commit message:* 
- refactor "loadMappings" functions
- trim values of XML elements/attributes
- clear mappings if the corresponding XML element exists
- add an example advancedsettings.xml with all default values
This pull request refactors `AdvancedSettings.cpp`. It removes redundant code and simplifies code regarding mappings. Also, tags are now trimmed and `*.mk3d` is added as a video format.
This PR also adds an example xml file that is based on your version posted [here](http://community.kvibes.de/topic/show/advanced-settings). I added missing tags and changed the values to MediaElch's defaults.
I'm not exactly sure what `<forceCache>` does. Could you explain that tag to me? :smile: 
This PR has one change regarding the XML. `useFirstStudioOnly` is no longer an XML tag but instead …
> Refactor AdvancedSettings; add example XML

- scrapers/TMDb.cpp
- scrapers/TMDb.h
- removes the dependency "QScript" from TMDb.cpp
- restructures TMDb.cpp (simplify request urls)
With this PR, the only files that still use QScript are `CustomMovieScraper.cpp` and `TMDbConcerts.cpp`. 
There was way to much copy&paste regarding the search/movie URL of TheMovieDb which makes changes to the URL difficult.  I created two methods that handle creating the search and movie URL. All parameter values are percent encoded. I also switched to enums for parameters to avoid typos.
There was also one bug that is now fixed:
```cpp
movie->setOverview(sc.property("overview").toString());
if (Settings::instance()->usePlotForOutline())
movie->setOutline(sc.property("overview").toString());
```
The outline was never set to the plot's value.
This PR should not break anything. Images are …
> Remove QScript from TMDb; restructure request urls

- smallWidgets/MusicTreeView.cpp
- smallWidgets/TvShowTreeView.cpp
- too long titles were broken into multiple lines
- instead uses an ellipsis ("...")
> [Tree View] Fix too long titles

- doc/advancedsettings.xml
- main.cpp
- settings/AdvancedSettings.cpp
- settings/AdvancedSettings.h
Allows specifying an interface language unequal to your system's.
> Add "locale" to advanced settings

- globals/DownloadManager.cpp
- only first and last thumbnail of episodes were downloaded
- download must only start if no other item is currently downloaded
> [MultiScraper] Fix missing thumbs

- scrapers/TMDb.cpp
- scrapers/TMDb.h
- scrapers/TMDbConcerts.cpp
- scrapers/TMDbConcerts.h
This PR will update the list of supported languages by TMDb.
Languages that are supported by TMDb but have not yet been added to this PR: `be-BY`, `bn-BD`, `ca-ES`, `ch-GU`, `eo-EO`, `eu-ES`, `fa-IR`, `hi-IN`, `id-ID`, `ka-GE`, `kn-IN`, `lt-LT`, `ml-IN`, `nb-NO`, `ro-RO`, `sk-SK`, `sr-RS`, `ta-IN`, `te-IN`, `th-TH`, `uk-UA`, `vi-VN`
*Links:*
- MediaElch Community Thread: http://community.kvibes.de/topic/show/the-movie-db-modified-pt-language
- Supported languages by TMDb: https://gist.github.com/bugwelle/3a9c10ae702440cda043f2568cf4ee46 (copied from: https://developers.themoviedb.org/3/configuration/get-primary-translations)
**What was changed?**
> Update languages supported by TMDb; better language handling

- trailerProviders/HdTrailers.cpp
- 5min has been down since 2014
- yahoo videos are redirected using JavaScript (downloaded PHP)
Fixes #445
> [HDTrailers] Filter invalid URLs

- mediaCenterPlugins/XbmcXml.cpp
- thumb url was written to episode nfo even if `writeThumbUrlsToNfo` was set to false
> [NFO] Fix thumb in episode if writeThumbUrlsToNfo is false

- travis-ci/package.sh
- `libmediainfo.0.dylib` was not found
- setting `LD_LIBRARY_PATH` to `MediaElch.app/Contents/Frameworks` helped
- implemented solution: I moved `libmediainfo.0.dylib` to `MacOS`
@Komet I'll merge this because it works. 
But I wonder: How would I solve this in a better way? I can't find where MediaInfo is linked and wonder how (or why) it is loaded. It seems I still have a lot to learn about linking.
*Update:* Nevermind, found it: https://github.com/MediaArea/MediaInfoLib/blob/master/Source/MediaInfoDLL/MediaInfoDLL.h#L135
> [Travis] Fix macOS streamdetails

- globals/TrailerDialog.cpp
This is a really strange solution, but only one I could find to fix this:
Qt 5.11 on macOS is extremely buggy!
> [macOS] Fixed Trailer Dialog

- concerts/ConcertController.cpp
- concerts/ConcertWidget.cpp
- data/StreamDetails.cpp
- data/StreamDetails.h
- downloads/ImportDialog.cpp
- export/ExportDialog.cpp
- globals/Filter.cpp
- image/Image.cpp
- image/Image.h
- image/ImageCapture.cpp
- mediaCenterPlugins/XbmcXml.cpp
- movies/MovieController.cpp
- movies/MovieWidget.cpp
- renamer/Renamer.cpp
- smallWidgets/FilterWidget.cpp
- smallWidgets/MediaFlags.cpp
- trailerProviders/HdTrailers.cpp
- trailerProviders/HdTrailers.h
- tvShows/TvShowWidgetEpisode.cpp
Depends on #494 
This PR replaces strings with scoped enums to ensure type safety.
I'll rebase this PR when #494 is merged.
> [StreamDetails] Use scoped enums instead of strings

- data/StreamDetails.cpp
- doc/advancedsettings.xml
- settings/AdvancedSettings.cpp
- the user is presented with an audio codec which
(if put in advancedsettings.xml) may not be used because
lowercase/uppercase may differ
- add "aac lc" to "aac" mapping
> [AdvancedSettings] Fix audio codec mapping

- .gitignore
- scripts/build-scripts/build_functions.sh
- scripts/build-scripts/check_dependencies.sh
- scripts/build-scripts/package_functions.sh
- scripts/build_release.sh
- scripts/package_release.sh
- scripts/utils.sh
- travis-ci/configure.sh
- travis-ci/install_dependencies.sh
- travis-ci/package.sh
- travis-ci/utils.sh
Added a script which will package MediaElch. Currently only AppImage is supported.
```
./package_release.sh linux appimage
Information used for packaging:
Git Date          = 2018-07-13 16:46:52 +0200
Git Hash          = 7177053
Date Hash         = 2018-07-13_14-47
MediaElch Version = 2.4.3-dev
Version Name      = 2.4.3-dev_2018-07-13_14-47_git--7177053
Do you want to package MediaElch for linux with these settings?
Press enter to continue
Checking dependencies for Linux AppImage
✔ ffmpeg installed
All dependencies installed.
Checking dependencies for Linux
✔ gcc installed
✔ g++ installed
✔ qmake installed
Checking package dependencies for Linux
✔ libcurl4-openssl-dev installed
✔ libmediainfo-dev installed
✔ libpulse-dev installed
✔ zlib1g-dev installed
✔ libzen-dev installed
All …
```
> [Build] Create package release script

- globals/TrailerDialog.cpp
For some reason that I just don't unterstand, Qt 5.11 couldn't find the correct slot in `TrailerDialog.cpp`.
> [TrailerDialog] Fix signal slot

- MediaElch.pro
- scrapers/AdultDvdEmpire.cpp
- scrapers/IMDB.cpp
- test/main.cpp
- test/qtCatchHelper.h
- test/scrapers/main.cpp
- test/scrapers/testAEBN.cpp
- test/scrapers/testAdultDvdEmpire.cpp
- test/scrapers/testHotMovies.cpp
- test/scrapers/testIMDb.cpp
- test/scrapers/testKinoDe.cpp
- test/scrapers/testTMDb.cpp
- test/scrapers/testVideoBuster.cpp
- thirdParty/catch2/catch.hpp
Commit message: 
- add tests for scraper searches
- fix ADE scraper
This PR adds some basic tests. We really need them. Scrapers break like once a few days...
With this we will have tests for searching movies so that broken scrapers like in #565 are found and fixed faster.
```sh
mkdir build
cd build 
qmake CONFIG+=test ..
make -j4
./mediaelch-test
```
Running it will look like this:
PS: I tried to find the most "normal" movie names for adult scrapers...
---------
QTest is not as powerful and easy to use. Catch2 is awesome :smiley:
> [Tests] Add first scraper online tests

- changelog.md
- scripts/build-scripts/package_functions.sh
- src/concerts/ConcertWidget.cpp
- src/mediaCenterPlugins/XbmcXml.cpp
- src/movies/MovieWidget.cpp
- src/music/MusicWidgetAlbum.cpp
- src/music/MusicWidgetArtist.cpp
- src/smallWidgets/TagCloud.cpp
- src/smallWidgets/TagCloud.h
- src/tvShows/TvShowWidgetTvShow.cpp
- travis-ci/package.sh
Fixes #554 
Fixes #488 by using a workaround.
Fixes a packaging problem introduced by #576
> [XML] Fix set name; [TagCloud] Only load 150 inactive tags

- MediaElch.pro
- src/export/ExportTemplateLoader.cpp
- src/tv_shows/TvShowUpdater.cpp
Some downstream package maintainers will resort to maintaining patches
against MediaElch sources to enable build against external quazip libraries.
Commit establishes a convenience CONFIG flag:
`CONFIG += USE_EXTERN_QUAZIP`
that enables a DEFINE statement that is used to switch out thirdparty/quazip
references with external quazip sources.
> Enable CONFIG setting for building against external quazip

- CMakeLists.txt
- cmake/coverage.cmake
From PR #756, comment was made for need to add commit to CMake Build system files as well.
This commit implements PR#756 into project CMake files.
Executing on the command line:
`cmake ... -DUSE_EXTERN_QUAZIP=ON ...`
will do the same as PR#756, that is internally set a flag in CMake to test, set a define
for project files during compile, and add the library reference to external libquazip5.
> Enable CONFIG setting for building against external quazip(CMake)

- CHANGELOG.md
- src/globals/DownloadManager.cpp
- src/globals/DownloadManager.h
The DownloadManager isn't really thread safe. I don't know how it worked in the past. Well, this is more like a quickfix that hopefully fixes  #716
> [DownloadManager] Use QMutex when assigning a download element value

- src/export/ExportTemplateLoader.cpp
- bug introduced in "[Project] Fix coverity warnings" : db6a5c4518354ef03d9d642e1d41070dcd94e7fc
> [Export] Fix empty export name

- src/settings/Settings.cpp
This fixes most of the gaps in the Media Elch's naming scheme for the artwork for different media types.
For more info refer to https://kodi.wiki/view/Artwork_types
Note: There are still some artwork types supported by Kodi but not by Media Elch. But most of the common ones should be covered.
Resolves: https://github.com/Komet/MediaElch/issues/781
> Fix/Rename for Kodi artwork types

- CHANGELOG.md
- src/ui/default.css
- Remove `border:none` from QTableWidget
- Note from Qt docs (QTableWidget):
https://doc.qt.io/qt-5/stylesheet-reference.html
"If you only set a background-color on a QTableCornerButton,
the background may not appear unless you set the border property
to some value. This is because, by default, the QTableCornerButton
draws a native border which completely overlaps the
background-color."
- bug introduced in 629786b2b4ee92c8ab6495b2ae2ffcdf243c3d64
(Mon Feb 18 08:45:19 2019 +0100)
> [Style] Fix label color not shown for movies

- CHANGELOG.md
- src/media_centers/kodi/MovieXmlReader.cpp
- src/media_centers/kodi/TvShowXmlReader.cpp
If an NFO contains a valid `<year>` tag but invalid `<premiered>` tag, the date was always set to an invalid `QDate` (the UI shows `2019`).
- related issue #821
> [Movie/TvShow] Only use premiered tag if it contains a valid date

- CHANGELOG.md
- MediaElch.pro
- src/data/CMakeLists.txt
- src/data/MediaInfoFile.cpp
- src/data/MediaInfoFile.h
- src/data/StreamDetails.cpp
- src/data/StreamDetails.h
- src/globals/Helper.cpp
- src/globals/Helper.h
- src/ui/small_widgets/MediaFlags.cpp
- fixes #797, related issue: #796
MediaInfoLib 18 and newer have changed quite a few properties. `Codec` is deprecated, `Format_Profile` may return nothing, etc.
This PR aims to make MediaElch compatible with the latest MediaInfoLib versions. A user on the [Kodi forum](https://forum.kodi.tv/showthread.php?tid=136333&pid=2910256#pid2910256) gave a few examples and I was able to reproduce these issues by using some [samples](https://kodi.wiki/view/Samples).
I had a look at TinyMediaManager and how they handle such stuff and copied some parts of their logic. A comments mentions this. A big THANK YOU to them. :-)
Ping @monisriz (as you had issues with audio codecs in the past)  
If you experience any issues after this PR is merged, please let me know. I've tested quite a few sample files and …
> [MediaInfoFile] Update audio recognition for latest MediaInfoLib (v19)

- CHANGELOG.md
- src/ui/tv_show/TvShowFilesWidget.cpp
- src/ui/tv_show/TvShowFilesWidget.h
- icon "sync" wasn't displayed and items weren't marked for sync
- fix #850
> [TvShowFilesWidget] Fix "mark for sync" feature

- CHANGELOG.md
- docs/advancedsettings.xml
- src/concerts/ConcertFileSearcher.cpp
- src/movies/MovieFileSearcher.cpp
- src/movies/MovieFileSearcher.h
- src/movies/MovieFilesOrganizer.cpp
- src/music/MusicFileSearcher.cpp
- src/settings/AdvancedSettings.cpp
- src/settings/AdvancedSettings.h
- src/settings/AdvancedSettingsXmlReader.cpp
- src/settings/AdvancedSettingsXmlReader.h
- src/tv_shows/TvShowFileSearcher.cpp
- src/ui/main/MainWindow.h
- test/unit/settings/testAdvancedSettings.cpp
- fix #840 
This PR adds an experimental feature that allows users to exclude certain files as well as directories. Only folder structures below the folders given in settings are checked and possibly excluded. No debug messages are given as this may spam the debug output if e.g. a folder exists in all movie directories. The patterns are regular expressions, so `<pattern applyTo="folders">.unknown</pattern>` will match not only `.unknown` but `aunknown`, etc. as well as the dot is a placeholder for "any character" in regular expressions.
- only folders can be filtered as we don't read any files (i.e. not songs)
> [AdvancedSettings] Add exclude patterns to filter files

- CHANGELOG.md
- src/tv_shows/TvShow.cpp
- src/tv_shows/TvShowEpisode.cpp
- src/tv_shows/TvShowFileSearcher.cpp
- src/tv_shows/TvShowModel.cpp
- src/tv_shows/TvShowModel.h
- src/tv_shows/model/README.md
- src/ui/downloads/ImportDialog.cpp
- src/ui/small_widgets/TvShowTreeView.h
- src/ui/tv_show/TvShowFilesWidget.cpp
- src/ui/tv_show/TvShowFilesWidget.h
- src/ui/tv_show/TvShowWidget.cpp
- src/ui/tv_show/TvShowWidgetEpisode.cpp
- src/ui/tv_show/TvShowWidgetSeason.cpp
- src/ui/tv_show/TvShowWidgetTvShow.h
Fix #789  
Fix #865
SeasonModelItem, etc. are not exactly models but only data containers
for the model.
The issue that this commit fixes is with the TvShow model, i.e. the model that is responsible for displaying all TV shows in a tree-like widget. When MediaElch reads the list of shows it manages, each show is appended to the model one at a time. The Qt View/Model for the TreeView requires us to call `beginInsertRows` before adding a row. This is required for the TreeView to know that a change occurs and that the underlying data is about to change. We do this for TV shows only. When we add seasons or even single episodes to the TV show model, we used the TvShowModelItem which isn't an QAbstractItemModel but only the container for the underlying data. The model does not notice that rows …
> [TvShowModel] Only allow changes to underlying data through model

- CHANGELOG.md
- MediaElch.pro
- src/scrapers/ScraperInterface.cpp
- travis-ci/docker/Dockerfile.build-opensuse-leap-15
- travis-ci/docker/Dockerfile.build-opensuse-leap-42.3
- travis-ci/docker/Dockerfile.build-opensuse-tumbleweed
- travis-ci/docker/Dockerfile.build-ubuntu-16.04
- travis-ci/docker/Dockerfile.build-ubuntu-18.04
- travis-ci/docker/Dockerfile.build-ubuntu-19.04
We still need to support Ubuntu 16.04 as it is still supported (LTS version)
> [Qt] Revert requirement of Qt 5.6 due to Ubuntu 16.04 being on Qt 5.5

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/scraper-does-not-work.md
- CHANGELOG.md
- CMakeLists.txt
- MediaElch.plist
- Version.h
- debian/changelog
- docs/admin/release.md
- obs/MediaElch.changes
- obs/MediaElch.spec
- obs/README.md
This PR prepares the release of MediaElch v2.6.4. Please note that I plan to release the next version on 2020-02-16 but if I for some reason cannot hold that deadline, it will be released a month later. :-)
Todo:
After merging this PR:
Ping @sumo300 (windows), @Komet (owner), @scottfurry (other linux repo)
To all packagers: There are two useful compile flags:
- `USE_EXTERN_QUAZIP` (see #756)
- `DISABLE_UPDATER`(see #763)
> [Release] Prepare release of v2.6.4

- CHANGELOG.md
- src/globals/ImageDialog.cpp
- src/scrapers/image/FanartTv.cpp
Fanart.tv may respond with a 404 message. As of 2020-02-23 this happens
for the show "For Life" which does not have any images on fanart.tv.
Prior to this commit, a non-user-friendly message was shown.
Fixes #900
> [Fanart] Explicitly handle 404 response

- CHANGELOG.md
- scripts/packaging/package.sh
- src/scrapers/movie/AEBN.cpp
- travis-ci/package.sh
`std::any_of(movie->actors().cbegin(), movie->actors().cend(),` did not
work because two temporary *different* QVector objects were used to
iterate the actors.
Fix #910
> [AEBN] Fix segmentation fault

- CHANGELOG.md
- src/movies/MovieModel.cpp
- src/movies/MovieProxyModel.cpp
Prior to this commit, movies were sorted by name (if "name" was
selected). This commit changes it to the sort title if it is present
and the movie name otherwise.
Fix #919
> [MovieProxy] Use a movie's sort title for sorting entries if set

- CHANGELOG.md
- src/scrapers/movie/TMDb.cpp
defaultLanguageKey() is supposed to return the language key, e.g. de-DE.
Prior to this commit however, only the language was returned, e.g. "de".
Due to this the combo box did not select the correct language and nearly
always selected "Arabic", i.e. the first entry.
Fix #916
> [TMDb] Fix defaultLanguageKey() and return the locale, not just language

- CHANGELOG.md
- src/concerts/ConcertFileSearcher.cpp
Due to a string comparison, scanning of concerts did not work on
Windows. That is because one of two paths (as strings) used the native
path separators (i.e. backslash) and one was "normalized" and used
the normal forward slash.
Fix #814
> [Concert] Fix scanning of concerts

- .travis.yml
- CHANGELOG.md
- src/globals/Helper.cpp
- src/globals/Helper.h
- src/ui/downloads/DownloadsWidget.h
- src/ui/downloads/MakeMkvDialog.cpp
- src/ui/small_widgets/MyTableWidgetItem.cpp
- src/ui/small_widgets/MyTableWidgetItem.h
Due to a bug, files above 2GB had the wrong file size. That is because
an integer (32bit) was used to store the file size in Byte.
Furthermore MediaElch showed file sizes in MiB, GiB, etc. even though
MB, GB, etc. were displayed.
Fix #829
> [DownloadWidget] Fix wrong file sizes

- src/ui/small_widgets/MyTableWidgetItem.cpp
Instead of showing both, the file size as a power of 1000 (kB, MB, GB) and as a power of 1024 (kiB, MiB, GiB) we now only show the former and display the latter as a tool tip.
> [Download Section] Show file size as a factor of 1024 in tool tip

- src/ui/export/ExportDialog.cpp
When developing an export-theme:
It is usual to export within minutes.
Currently the minutes are the "smallest change", which can collide frequently.
with this RP the seconds are appended, and prevent naming-collisions.
I think this will not cause any harm to existing documentation. But it could break automation.
> [export] adding seconds to export folder

- CHANGELOG.md
- src/globals/ComboDelegate.cpp
- src/ui/tv_show/TvShowWidgetEpisode.cpp
Two missing signal/slot handlers were the cause that writers/
directors were not saved after being manually edited.
Fix #933
> [TvShow] Fix editing of writers/directors

- .gitignore
- CHANGELOG.md
- src/image/ImageCapture.cpp
- src/image/ImageCapture.h
- src/ui/movies/MovieWidget.cpp
- src/ui/movies/MovieWidget.h
- src/ui/small_widgets/ClosableImage.cpp
- src/ui/small_widgets/ClosableImage.h
- src/ui/tv_show/TvShowWidgetEpisode.cpp
- src/ui/tv_show/TvShowWidgetEpisode.h
- travis-ci/package.sh
This PR makes it possible to click the "grab a screenshot" button
which generates a random screenshot with the desired poster size in the
aspect ratio of 2:3.
Note that the image is cropped from the screenshot's center. For example, take the following screenshot of the open source movie "Sintel" ( https://durian.blender.org/ ):
It will be cropped to: 
Fix  #934
>  [MovieWidget] Make it possible to generate the poster from a screenshot

- src/data/Database.cpp
- src/data/Database.h
- src/tv_shows/TvShowFileSearcher.cpp
- src/tv_shows/TvShowFileSearcher.h
- src/ui/tv_show/TvShowFilesWidget.cpp
`database().shows(path);` was called which creates new `TvShow*`
instances where only the count was interesting. This commit removes
one such case. This was furthermore a memory leak as the TV shows
were never deleted afterwards.
> [TvShow] Don't load shows from database when only count is used

- CHANGELOG.md
- MediaElch.pro
- src/CMakeLists.txt
- src/log/CMakeLists.txt
- src/log/Log.cpp
- src/log/Log.h
- src/main.cpp
- src/ui/main/AboutDialog.cpp
**[Log] Respect `QT_MESSAGE_PATTERN` and use better defaults** 
Previously, MediaElch did not respect Qt's environment variable
`QT_MESSAGE_PATTERN`.  That environment variable can be used to format
logging messages.  MediaElch now uses that environment variable and
changes its default logging pattern.  In debug mode the default pattern
uses colors if the console supports it.  It may be expanded to release
mode as well.
> [Log] Respect QT_MESSAGE_PATTERN and use better defaults

- CHANGELOG.md
- MediaElch.pro
- src/globals/CMakeLists.txt
- src/globals/Manager.cpp
- src/globals/Manager.h
- src/globals/Meta.cpp
- src/globals/Meta.h
- src/globals/TrailerDialog.cpp
- src/globals/TrailerDialog.h
- src/scrapers/music/TvTunes.cpp
- src/scrapers/music/TvTunes.h
- src/scrapers/trailer/HdTrailers.cpp
- src/scrapers/tv_show/TheTvDb.cpp
- src/ui/main/MainWindow.cpp
- src/ui/movies/MovieWidget.cpp
- src/ui/tv_show/TvShowWidgetTvShow.cpp
- src/ui/tv_show/TvTunesDialog.cpp
- src/ui/tv_show/TvTunesDialog.h
Fix #940
**[TrailerDialog] Fix downloading trailers for many movies**  
If the trailer dialog window was closed using the window frame's close
button ("x") instead of the button labeled "Close", the dialog was
destroyed and reopening it resulted in an empty dialog window.
There is no need to use a singleton for the TrailerDialog so it was
**[TvTunes] Fix crash when dialog is closed and re-opened for other show**  
If the TvTunes dialog is opened the first time for a show, it downloads
some resources. This download does not stop when the dialog is closed.
If the dialog is now reopened (e.g. for another show) we get a race
condition because two threads try to dequeue a list with only one item.
Because an empty list cannot be dequeued, `abort()` is called by Qt.
The fix is simple: Use one …
> [Dialogs] Fix downloading trailers for many movies and tv tunes for shows

- CHANGELOG.md
- scripts/create_fakes.sh
- scripts/library/downloads.txt
- src/movies/MovieController.cpp
- src/ui/movies/MovieWidget.cpp
If the user changes the movie's runtime and saves it, it may be set to
0 if "Automatically load and save stream details from file" is enabled.
This commit first checks if the detected runtime is greater than 0.
Fix #604
> [Movie] Don't save runtime from file if it cannot be detected

- CHANGELOG.md
- src/ui/tv_show/TvShowWidgetSeason.cpp
TheTvDb may not return posters for a certain seasons. However users may
want to select TvShow posters for a season.
Fix #600
> [TvShow] Also load TV show posters when searching for new season posters

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/scraper-does-not-work.md
- CHANGELOG.md
- CMakeLists.txt
- MediaElch.plist
- Version.h
- debian/changelog
- docs/admin/release.md
- obs/MediaElch.changes
- obs/MediaElch.spec
- obs/README.md
This PR prepares the release of MediaElch v2.6.6. Please note that I plan to release the next version on 2020-04-19 but if I for some reason cannot hold that deadline, it will be released a week later. :-)
Todo:
After merging this PR:
Ping @sumo300 (windows), @Komet (owner), @scottfurry (other linux repo)
To all packagers: There are two useful compile flags:
- `USE_EXTERN_QUAZIP` (see #756)
- `DISABLE_UPDATER`(see #763)
> [Release] Prepare release of v2.6.6

- CHANGELOG.md
- src/export/SimpleEngine.cpp
>  [Export] Allow using episode images in TV show overview 

- CHANGELOG.md
- src/export/SimpleEngine.cpp
- src/export/SimpleEngine.h
- src/tv_shows/TvShowEpisode.cpp
- src/tv_shows/TvShowEpisode.h
In a previous commit, images were replaced last for TV shows so that the
inner most block is used for images. This lead to a stupid bug because
the "replaceImages" call was not called unless a `SEASON` block existed.
If it didn't, an early return was triggered.
This commit also introduces some minor changes to image-replacement for
concerts and movies. Image tags are only replaced if the tag is actually
used.
Furthermore, some minor refactoring was done.
Fix #961
> [Export] Fix replacing TV show images in tvshows.html

- CHANGELOG.md
- src/movies/file_searcher/MovieFileSearcher.cpp
- src/movies/file_searcher/MovieFileSearcher.h
Previously, folder's like `something.mkv` inside an actual movie folder
were added to the movie's file list. Now only files are added or folders
that have a special structure like DVD or BluRay folders.
Fix  #977
> [MovieFileSearcher] Only add directory to movie files if it's a DVD/BR

- .travis.yml
- CHANGELOG.md
- MediaElch.pro
- src/scrapers/tv_show/thetvdb/EpisodeLoader.cpp
- src/scrapers/tv_show/thetvdb/EpisodeLoader.h
- src/scrapers/tv_show/thetvdb/EpisodeParser.cpp
- src/settings/Settings.cpp
- src/settings/Settings.h
- src/tv_shows/CMakeLists.txt
- src/tv_shows/SeasonOrder.cpp
- src/tv_shows/SeasonOrder.h
- src/ui/tv_show/TvShowMultiScrapeDialog.cpp
- src/ui/tv_show/TvShowMultiScrapeDialog.h
- src/ui/tv_show/TvShowMultiScrapeDialog.ui
- src/ui/tv_show/TvShowSearch.cpp
- src/ui/tv_show/TvShowSearch.h
- src/ui/tv_show/TvShowSearch.ui
- test/scrapers/thetvdb/testShowLoader.cpp
Season can be ordered by aired date, dvd order or sometimes even anime
order. This enum class will hold all possible values in the future.
Currently only "aired" and "dvd" order are supported.
> [TvShows] Add SeasonOrder enum to distinguish ordering of seasons

- MediaElch.pro
- src/ui/settings/CMakeLists.txt
- src/ui/settings/ScraperSettingsWidget.cpp
- src/ui/settings/ScraperSettingsWidget.h
- src/ui/settings/ScraperSettingsWidget.ui
- src/ui/settings/SettingsWindow.ui
- src/ui/settings/TvScraperSettingsWidget.cpp
- src/ui/settings/TvScraperSettingsWidget.h
- src/ui/settings/TvScraperSettingsWidget.ui
Move the UI part of the TV scraper settings into a custom widget class.
This makes it easier to refactor it for future scraper changes.
Needed for #972
> [Settings] Refactor TV scraper settings into custom widget class

- src/data/Locale.cpp
- src/data/Locale.h
- src/scrapers/image/FanartTv.cpp
- src/scrapers/image/FanartTv.h
- src/scrapers/image/FanartTvMusic.cpp
- src/scrapers/image/FanartTvMusic.h
- src/scrapers/image/FanartTvMusicArtists.cpp
- src/scrapers/image/FanartTvMusicArtists.h
- src/scrapers/image/ImageProviderInterface.h
- src/scrapers/image/TMDbImages.cpp
- src/scrapers/image/TMDbImages.h
- src/scrapers/image/TheTvDbImages.cpp
- src/scrapers/image/TheTvDbImages.h
These methods are not yet used, but required for the TV scraper refactoring. The languages are only used for searching for TV shows by title.
> [ImageProviders] Add supportedLanguages() method

- src/data/Locale.cpp
- src/data/Locale.h
- src/scrapers/movie/TMDb.cpp
The default constructor is required for some Qt containers like QVector
on certain platforms (Linux).
Fix #999
> [Locale] Add missing default constructor

- travis-ci/docker/Dockerfile.build-windows
The update to CMake 3.17 in mxe produced this issue. We were simply missing some headers.
> [Docker] Add missing libssl-dev dependency for mxe-cmake

- .clang-format
- .travis.yml
- scripts/docker/Dockerfile
- scripts/docker/README.md
- scripts/docker/install_cmake.sh
- scripts/docker/install_iwyu.sh
- scripts/run_clang_format.sh
- src/data/MediaInfoFile.cpp
- src/export/ExportTemplateLoader.cpp
- src/globals/Helper.cpp
- src/log/Log.cpp
- src/tv_shows/TvShowUpdater.cpp
- src/ui/main/MainWindow.cpp
- src/ui/music/MusicWidgetAlbum.cpp
- src/ui/notifications/Notificator.cpp
We now format our code base using clang-format-10 and no longer with
clang-format-9.  Also update clang and gcc dependencies to clang-10 and
gcc10 as well as CMake.
This requires us to use Ubuntu Focal Fossa in TravisCI.
For easier use on macOS, the `run_clang_format.sh` script now also
checks for the MacPorts version of clang-format.
> [scripts] Update clang-format and other dependencies

- CHANGELOG.md
- src/main.cpp
- src/settings/AdvancedSettings.cpp
- src/settings/AdvancedSettings.h
The article at [1] describes how to properly load translations.  While
MediaElch did load it partially correct, we had some special coding
that is now removed.
[1]: https://www.kdab.com/fixing-a-common-antipattern-when-loading-translations-in-qt/
> [i18n] Use proper translation loading

- CHANGELOG.md
- src/ui/main/MainWindow.cpp
A simple help menu for macOS which contains some useful URLs.
> [Menu] Add help menu for macOS

- CHANGELOG.md
- docs/advancedsettings.xml
- src/main.cpp
- src/settings/AdvancedSettings.cpp
- src/settings/AdvancedSettings.h
- src/settings/AdvancedSettingsXmlReader.cpp
This commit introduced the option `<stylesheet>` which allows users to
use a custom CSS file.  This is intended for developing MediaElch themes
(for the main window).
-------
Haven't tested this PR, yet. Just coded this off the top of my head.
> [AdvancedSettings] Add possibility to use custom CSS file

- src/globals/Helper.cpp
- src/ui/default.css
Previously the button style was set in our C++ code.  But this means
that user cannot style the buttons using a custom CSS file.
This commit moves the style to the CSS file which also makes our code
more readable.
FYI, @ioogithub More buttons can be styled with the CSS file. :-)
> [Style] Move button stylesheet to CSS file

- .gitignore
- src/settings/Settings.cpp
- src/settings/Settings.h
Also remove unused option `m_debugLogPath` (it is set in advanced settings).
> [Settings] Use constants to avoid spelling errors

- src/cli/main.cpp
- src/concerts/ConcertController.cpp
- src/data/ImageCache.cpp
- src/globals/DownloadManager.cpp
- src/globals/DownloadManagerElement.h
- src/globals/Meta.cpp
- src/globals/Meta.h
- src/main.cpp
- src/movies/MovieController.cpp
- src/music/AlbumController.cpp
- src/music/ArtistController.cpp
- src/network/NetworkManager.cpp
- src/network/NetworkManager.h
- src/scrapers/image/FanartTv.cpp
- src/ui/imports/ImportDialog.cpp
- src/ui/main/MainWindow.cpp
- src/ui/movie_sets/SetsWidget.cpp
- src/ui/tv_show/TvShowMultiScrapeDialog.cpp
- src/ui/tv_show/TvShowWidgetEpisode.cpp
- src/ui/tv_show/TvShowWidgetSeason.cpp
- src/ui/tv_show/TvShowWidgetTvShow.cpp
- test/integration/main.cpp
- test/scrapers/main.cpp
- test/unit/main.cpp
Fix  #1073
-------
I previously assumed that we had a threading issue.  But this is not
the case because connect() calls methods of DownloadManager only in one
thread, DownloadManager's thread.
But I forgot that signals (e.g. "emit sigFinished") call their slots
_immediately_ by default. This means we could end up in inconsistent
states because member variables are changed while we are still inside a
method that depends on them or has a previous state.  For example:
```
addDownload()
startNextDownload();
on finished: downloadFinished()
emit sigDownloadFinished(elem);
some slot calls addDownload, m_currentDownloadElement changes
emit sigElemDownloaded(elem);
may emit wrong element
```
To avoid this, I've adapted all places where a connect() to this
download manager is used.  Those places …
> [Downloads] Use a queued connection for the download manager everywhere

- src/ui/main/Message.cpp
- src/ui/main/Message.h
- src/ui/notifications/NotificationBox.cpp
- src/ui/notifications/NotificationBox.h
removeWidget() does not change the widget's ownership.
The ownership was transferred to the layout by calling addWidget().
Because we still want to delete the widget, first hide it then
change ownership and only after that delete it.
On systems with Kvantum theme, e.g Manjaro with XFCE, MediaElch
would crash due to SEGFAULT.
-----
This should:
- fix #1050
- fix #1060
- fix  #976
- fix #1073
> [NotificationBox] Hide message and change parent before deleting it

- CHANGELOG.md
- src/globals/DownloadManager.cpp
- src/globals/DownloadManager.h
- src/network/NetworkReplyWatcher.cpp
- src/network/NetworkReplyWatcher.h
Currently based on #1076
Previously, only one file was downloaded in parallel. We didn't use the users bandwidth. I refactored the code so that we now download up to 6 elements in parallel. Why 6? Because that's what [qnetworkaccessmanager](https://doc.qt.io/qt-5/qnetworkaccessmanager.html) does per default.
I (with a small 30MBit internet connection) can now load movies way faster.
```
12 years a slave
TMDb
Danish
52 Downloads
__Pre-Change__
Run 1)
Start: 16:02:12
End:   16:02:39
=> 27 seconds
Run 2) 
Start: 16:03:07
End:   16:03:24
=> 27 seconds
__Parallel__
Run 1)
Start: 15:59:27
End:   15:59:34
=> 7 seconds
Run 2)
Start: 16:00:43
End:   16:00:50
=> 7 seconds
```
3-4 times faster :tada:
I have learned from my mistakes in the past and won't merge this for the next MediaElch release. I …
> [DownloadManager] Run up to 6 downloads in parallel; refactor

- CHANGELOG.md
- src/settings/Settings.cpp
- src/settings/Settings.h
- src/ui/tv_show/TvShowCommonWidgets.cpp
- src/ui/tv_show/TvShowCommonWidgets.h
- src/ui/tv_show/TvShowMultiScrapeDialog.cpp
- src/ui/tv_show/TvShowMultiScrapeDialog.h
- src/ui/tv_show/TvShowSearchWidget.cpp
- src/ui/tv_show/TvShowSearchWidget.h
Episode and show details were not correctly stored.  MediaElch now uses
the scraper's id to store the selected episode and show details.
The same applies to the selected language.
---------
Fix #801
> [TvShowSearch] Fix load/store of episode/show details and language

- src/file/NameFormatter.cpp
- test/unit/file/testNameFormatter.cpp
Just replacing it is better than ignoring the word.
Fix #1131
> [NameFormatter] If exclude-words contain special characters, replace it

- .gitignore
- src/scrapers/movie/imdb/CMakeLists.txt
- src/scrapers/tv_show/ShowMerger.cpp
- src/tv_shows/TvShowEpisode.cpp
- src/tv_shows/TvShowEpisode.h
- src/ui/tv_show/TvShowWidgetEpisode.cpp
* Add field, getter and setter for wanting to download thumbnail (`m_want_thumbnail_download`)
* Add detection of `EpisodeScraperInfo::Thumbnail` in `copyDetailsToEpisode` to check if thumbnail was selected in episode scraper settings
* Fix IMDB scraper's CMakeLists.txt (for case-sensitive filesystem)
* Add CLion-specific folders in .gitignore
> [TvShowEpisode] Disable thumbnail download if not wanted 

- CHANGELOG.md
- src/globals/Helper.cpp
- src/globals/Helper.h
- src/renamer/ConcertRenamer.cpp
- src/renamer/EpisodeRenamer.cpp
- src/renamer/MovieRenamer.cpp
- src/renamer/Renamer.cpp
- src/renamer/RenamerDialog.cpp
- src/settings/DataFile.cpp
- src/ui/imports/ImportDialog.cpp
- src/ui/imports/MakeMkvDialog.cpp
Leading dots indicate hidden files on Unix systems.
Fix #1150
Tested with `.....Movie Name          Part 2`. Seems to work just fine. :-)
> [Renamer] Remove leading dots

- src/export/CsvExport.cpp
- src/export/CsvExport.h
- src/ui/export/CsvExportDialog.cpp
- src/ui/export/CsvExportDialog.h
- src/ui/export/CsvExportDialog.ui
Part of #585
Currently only some fields are supported:
```
TvField::ShowTitle
TvField::ShowImdbid
TvField::ShowTmdbid
TvField::EpisodeSeason
TvField::EpisodeNumber
TvField::EpisodeTitle
TvField::EpisodeOverview
```
Just quickly added some fields. @GarfieldS  What fields would like to have? I'm unsure about adding e.g. the show's overview because having that for each episode (i.e. for each row) is _a lot_ of extra text.
> [CSV Export] Add first basic TV show/episode export

- src/media_centers/KodiXml.cpp
- src/media_centers/KodiXml.h
- src/media_centers/kodi/v17/EpisodeXmlWriterV17.cpp
Avoid the "changed" state when reloading.
> [Episode] Write empty streamdetails if they were loaded once

- CHANGELOG.md
- MediaElch.plist
Make it possible to use the builtin graphics card instead of the
discrete one.
Fix #702
Before
After
Tested on macOS 11.1
> [macOS] Set NSSupportsAutomaticGraphicsSwitching to true

- CHANGELOG.md
- src/data/MediaInfoFile.cpp
Due to an incorrect regular expression, audio channels were no longer
detected.  The issue was that `*?` means "zero-or-more" in a non-greedy
way.  Because it is non greedy and everything after `\d` is optional as
well, it always matched _nothing_.
> [MediaInfoFile] Fix audio-channel detection

- CHANGELOG.md
- src/settings/Settings.cpp
- src/ui/tv_show/TvShowCommonWidgets.cpp
On fresh installations, `scraperInfosShow()` will return no details at
all.  To avoid that the user accidentally misses to enable checkboxes
on the episodes tab, enable all details per default.
--------
Fix #1189
> [TVShowSearch] Select all episode/show details if non were selected

- CHANGELOG.md
- MediaElch.pro
- src/file/CMakeLists.txt
- src/file/FilenameUtils.cpp
- src/file/FilenameUtils.h
- src/globals/Helper.cpp
- src/globals/Helper.h
- src/movies/file_searcher/MovieFileSearcher.cpp
- src/movies/file_searcher/MovieFileSearcher.h
- src/settings/DataFile.cpp
- test/unit/CMakeLists.txt
- test/unit/file/testStackedBaseName.cpp
Fix #1194
------------
It returned the wrong basename for: `Captain.The.Great.mkv`
That was because no delimiter between the title and "ptN"/"dvd-N" was
required and instead of using numbers like `pt1` one could also use
`pta`. And this matches the word `captain`.
> [File] Fix stackedBaseName() for names that contain "Captain"

- src/data/StreamDetails.cpp
MediaElch previously for some reason only used know audio codecs
for the renamer.
See #1212
> [StreamDetails] Also use unknown audio codecs

- CHANGELOG.md
- src/renamer/RenamerDialog.cpp
- src/renamer/RenamerDialog.ui
- src/renamer/RenamerPlaceholders.cpp
- src/renamer/RenamerPlaceholders.ui
- src/ui/main/MainWindow.cpp
> [Renamer] Use scroll view to avoid dialogs that are too large

- src/file/NameFormatter.cpp
- src/movies/Movie.cpp
- src/movies/file_searcher/MovieFileSearcher.cpp
- src/movies/file_searcher/MovieFileSearcher.h
The Nameformatter is a hot path in MediaElch. And as it turns out, the call to `QRegularExpression::optimize` takes about 50% of the time loading new movies.
Before
```
[MovieFileSearcher] Reloading took 5276 ms
```
After
```
[MovieFileSearcher] Reloading took 3859 ms
```
We may cache Regular expression in the future.
> [NameFormatter] Re-use regular expression object for better performance

- CHANGELOG.md
- MediaElch.pro
- src/data/Database.cpp
- src/data/Database.h
- src/movies/CMakeLists.txt
- src/movies/MovieModel.cpp
- src/movies/MovieModel.h
- src/movies/file_searcher/MovieDirectorySearcher.cpp
- src/movies/file_searcher/MovieDirectorySearcher.h
- src/movies/file_searcher/MovieFileSearcher.cpp
- src/movies/file_searcher/MovieFileSearcher.h
- src/scrapers/image/ImageProvider.h
- src/ui/movies/MovieFilesWidget.cpp
- MediaElch now searches for movies in parallel (#1230)  
Improvements can vary. During tests on different hard drives with
1000 movie directories, the time improvements were:
- 3.8s -> 1.3s (SSD)
- 4.1s -> 1.4s (HDD)
> [MovieFileSearcher] Do search in parallel

- CHANGELOG.md
- src/data/Database.cpp
- src/movies/Movie.cpp
The filename was interpreted as a global pattern, e.g. `Movie[BLURAY]`
would be interpreted as the regular expression `Movie(?:B|L|U|R|A|Y)`.
> [Movie] Fix local trailer search for names containing square brackets

- src/file/FilenameUtils.cpp
- src/file/FilenameUtils.h
- src/movies/file_searcher/MovieDirectorySearcher.cpp
This avoid cases where files appear before the movie's main file
because e.g. space comes before a dot.
> [Movie] Sort files without using file extension

- src/movies/file_searcher/MovieDirectorySearcher.cpp
- src/movies/file_searcher/MovieFileSearcher.cpp
A database connection can only be used in one thread.  The "getLabel"
call was called from multiple connections.
Fix #1245
> [MovieDirectorySearcher] Move database call to main thread

- src/export/ExportTemplateLoader.cpp
- src/globals/Actor.cpp
- src/globals/Helper.cpp
- src/network/NetworkRequest.cpp
- src/scrapers/movie/adultdvdempire/AdultDvdEmpire.cpp
- src/scrapers/movie/ofdb/OFDb.cpp
- src/scrapers/movie/tmdb/TmdbMovie.cpp
- src/scrapers/music/UniversalMusicScraper.cpp
- src/scrapers/trailer/HdTrailers.cpp
- src/settings/AdvancedSettings.cpp
- src/settings/AdvancedSettings.h
- src/settings/AdvancedSettingsXmlReader.cpp
- src/settings/Settings.cpp
- src/ui/concerts/ConcertFilesWidget.cpp
- src/ui/concerts/ConcertFilesWidget.h
- src/ui/main/AboutDialog.cpp
- src/ui/main/MainWindow.cpp
- src/ui/main/Navbar.cpp
- src/ui/main/Update.cpp
- src/ui/movies/MovieFilesWidget.cpp
- src/ui/movies/MovieFilesWidget.h
- src/ui/small_widgets/AlphabeticalList.cpp
- src/ui/small_widgets/SearchOverlay.cpp
- test/helpers/matchers.cpp
- test/helpers/matchers.h
- test/scrapers/testTmdbMovie.cpp
This commit has some fixes for Qt6.  Some deprecated enums/methods
were replaced.  Comparisons between QStringView and char* required
either QStringView on the right-hand-side or QLatin1String.  We use
the latter now as that's supported on older Qt versions as well.
Some unused `QRegEx` includes were removed.
Some conditionals were used, e.g. for method calls that are required
in Qt5 but are the default (and therefore removed) in Qt6.
This commit does NOT make MediaElch compatible with Qt6.
We still use QRegEx in a lot of places.  Furthermore, we have to wait
for Qt 6.2 to finally get QMultiMediaWidgets.
> [Project] More changes towards Qt6 compatibility 

- src/cli/main.cpp
- src/file/Path.h
- src/globals/Globals.h
- src/globals/Meta.h
- src/globals/ScraperInfos.h
- src/network/CMakeLists.txt
- src/tv_shows/EpisodeNumber.h
- src/tv_shows/SeasonNumber.h
- src/tv_shows/SeasonOrder.h
- src/ui/music/MusicFilesWidget.cpp
- src/ui/settings/GlobalSettingsWidget.cpp
- src/ui/tv_show/TvShowFilesWidget.cpp
- test/integration/media_centers/testKodi_v18_concert.cpp
This commit has some fixes for Qt6.  These changes include:
- use size_t instead of uint for qHash()'s return type
- Qt6 has some other defaults
- Use QProxyModel's `filterRegularExpression` instead of `filterRegExp`
Because we still support Qt 5.6, we have to use a few macros.
> [Project] More changes towards Qt6 compatibility

- CHANGELOG.md
- src/movies/MovieModel.cpp
- src/movies/MovieModel.h
- src/ui/movies/MovieFilesWidget.cpp
- src/ui/movies/MovieFilesWidget.ui
- src/ui/tv_show/TvShowFilesWidget.ui
Some Qt version apparently increased the default "minimum section size"
to 41px. But our icons are just 16px wide so there was a lot of
white-space.  Even though we explicitly set the column width to "22",
it was ignored because the minimum width was higher.
This commit fixes the huge space between icons.
Fix https://github.com/Komet/MediaElch/issues/793
| Before | After |
|:-----:|:-----:|
| tv shows | 
| ![Screenshot_20210331_181801](https://user-images.githubusercontent.com/1667306/113178216-a77ca400-924e-11eb-86ad-742e918b86cc.png) | ![Screenshot_20210331_182003](https://user-images.githubusercontent.com/1667306/113178231-ab102b00-924e-11eb-8f10-77185dd4dc3d.png) |
| movies |  |
| ![Screenshot_20210331_183043](https://user-images.githubusercontent.com/1667306/113178837-443f4180-924f-11 …
> [UI] Fix large icon column sizes 

- src/ui/small_widgets/RatingSourceDelegate.cpp
I didn't know that editable QComboBoxes existed so I used a line edit
before.  A ComboBox, however, is more convenient.
We still add a completer.
> [Ratings] Use editable QComboBox for rating source

- CHANGELOG.md
- src/ui/main/MyIconFont.cpp
The spacing was too high.  The reason for this was that the font ""
(empty string) was used.  This must have used some font with high
spacing.  We now simply use an empty QFont and set the font size
explicitly.
> [MainWindow] Fix "new" media count on macOS

- src/ui/settings/TvScraperSettingsWidget.ui
For some reason it was only cut off for "Custom TV Scraper"
> [TvScraperSettings] Avoid description being cut off

- CHANGELOG.md
- data/MediaElch.qrc
- data/icons/actions/16/add-subtitle.svg
- data/icons/actions/16/tag.svg
- data/icons/actions/22/add-subtitle.svg
- data/icons/actions/22/tag.svg
- src/data/StreamDetails.cpp
- src/data/StreamDetails.h
- src/movies/MovieModel.cpp
- src/movies/MovieModel.h
- fix #795
- fix https://github.com/Komet/MediaElch/issues/425
TODO
> [MediaStatusColumn] Add columns for subtitles and tags

- debian/copyright
- obs/MediaElch.spec
Our file "COPYRIGHT" has been LGPL-3 for a long time.
For some reason, the copyright files in our packaging files for
Debian and openSUSE were wrong.
As far as I can see, we use "LGPL-3.0-only".
-------------
@Komet I need approval from your side. As per mail, LGPLv3 is correct but I'm unsure about the "-only" suffix. :)
> [Packaging] Fix copyright string "LGPL-2.1" -> "LGPL-3.0"

- .ci/docker/Dockerfile.build-opensuse-leap-15
- .ci/docker/Dockerfile.build-opensuse-leap-42.3
- .ci/docker/Dockerfile.build-opensuse-tumbleweed
- .ci/docker/Dockerfile.build-ubuntu-16.04
- .ci/docker/Dockerfile.build-ubuntu-18.04
- .ci/docker/Dockerfile.build-ubuntu-20.04
- .ci/docker/Dockerfile.ci.linux
- .ci/docker/docker-build-dist.sh
- src/data/ImageCache.cpp
- src/scrapers/imdb/ImdbApi.h
- src/scrapers/music/AllMusic.h
- src/scrapers/music/MusicBrainz.h
- src/scrapers/music/TheAudioDb.h
- src/scrapers/tmdb/TmdbApi.h
- src/scrapers/tv_show/thetvdb/TheTvDbApi.h
- src/scrapers/tv_show/thetvdb/TheTvDbEpisodesParser.h
- src/scrapers/tv_show/tvmaze/TvMazeApi.h
- third_party/kfts/kfts_fuzzy_match.h
This PR fixes compilation issues with Qt 5.6 and therefore on some older distributions.
TODO:
> [CI] Add missing Qt SVG module to docker files

- CHANGELOG.md
- src/scrapers/tv_show/ShowMerger.cpp
- src/scrapers/tv_show/custom/CustomEpisodeScrapeJob.cpp
- src/scrapers/tv_show/custom/CustomShowScrapeJob.cpp
Previously, when TMDb was NOT used for anything, TheTvDb/IMDb/... IDs
were not copied so no data was loaded.
This commit fixes this bug by forcing some details to be copied
(with IDs).
> [CustomTvScraper] Do not fail if TMDb isn't used for anything

- src/ui/main/MainWindow.cpp
I accidentally left in this code. It was only meant for screenshots.
> [MainWindow] Fix loading of MainWindow size

- CHANGELOG.md
- src/tv_shows/TvShowFileSearcher.cpp
- test/unit/tv_shows/testTvShowFileSearcher.cpp
We did not properly set the offset when we switched to
`QRegularExpression`.  This commit fixes the incorrect episode
detection.
---------
See https://www.kodinerds.net/index.php/Thread/14560-MediaElch-MediaManager-for-Mac-Linux-Win/?postID=642371#post642371
> [TvShow] Fix episode detection for filenames that start with show name

- src/ui/concerts/ConcertFilesWidget.cpp
- src/ui/movies/MovieFilesWidget.cpp
- src/ui/tv_show/TvShowFilesWidget.cpp
- src/ui/tv_show/TvShowFilesWidget.h
Before, double clicking an entry worked great. Now, add a context menu
entry as well.
------------
See  #1305
> [FilesWidget] Add "Play" context menu entry

- .ci/ci_utils.sh
- CHANGELOG.md
- src/movies/file_searcher/MovieDirectorySearcher.cpp
- src/movies/file_searcher/MovieDirectorySearcher.h
- src/movies/file_searcher/MovieFileSearcher.cpp
- src/music/MusicModel.cpp
- src/tv_shows/TvShowFileSearcher.cpp
- src/tv_shows/TvShowModel.cpp
It could happen that we run multiple times into `onDirectoryLoaded()`
at once because of the call to `QApplication::processEvents();`.
This also meant that it could happen that the searchers are already
deleted before we return to the normal control flow in the first
call to `onDirectoryLoaded()`.  All references to `searcher` after
`QApplication::processEvents();` were therefore use-after-free bugs.
-----------
See #1316, #1315
> [MovieFileSearcher] Copy "searcher" data QApplication::processEvents(); 

- src/data/Actor.cpp
- src/scrapers/movie/aebn/AEBN.cpp
- src/scrapers/movie/aebn/AEBN.h
- src/scrapers/movie/imdb/ImdbMovie.cpp
- src/scrapers/movie/imdb/ImdbMovie.h
- src/scrapers/movie/tmdb/TmdbMovie.cpp
- src/scrapers/movie/tmdb/TmdbMovie.h
- src/ui/small_widgets/FilterWidget.cpp
- src/ui/small_widgets/FilterWidget.h
- src/ui/small_widgets/MyLineEdit.cpp
- src/ui/small_widgets/MyLineEdit.h
`Actor` is not a QObject class and we therefore have to delete it
explicitly.  In `clear()` we do that by calling `qDeleteAll()` but
not in `removeActor()`.
------------
As reported in https://github.com/Komet/MediaElch/issues/1315#issuecomment-835861035
> [Actor] Fix memory leak in `removeActor()`

- .ci/ci_utils.sh
- scripts/quick_checks.sh
- src/concerts/ConcertController.cpp
- src/file/NameFormatter.cpp
- src/file/NameFormatter.h
- src/globals/ImageDialog.cpp
- src/movies/MovieController.cpp
- src/movies/MovieFilesOrganizer.cpp
- src/tv_shows/TvShow.cpp
- src/ui/imports/ImportDialog.cpp
- test/unit/file/testNameFormatter.cpp
There is only one instance of this class (singleton).  While I
mostly dislike singletons, in this case there are reasons.  If we
do not use a singleton and do not store QRegularExpression objects,
each movie that is loaded has to instantiate all QRegularExpressions
for the "exclude word list".  Due to JIT compilation, this has
a _huge_ time disadvantage.  In some tests, 50% of the time went
into the NameFormatter prior to using a singleton.
See #1229 for more details.
> [NameFormatter] Use singleton again

- CHANGELOG.md
- src/data/Database.cpp
- src/data/Database.h
- src/log/Log.cpp
- src/log/Log.h
- src/media_centers/KodiXml.cpp
- src/movies/file_searcher/MovieDirectorySearcher.cpp
- src/movies/file_searcher/MovieDirectorySearcher.h
- src/movies/file_searcher/MovieFileSearcher.cpp
- src/movies/file_searcher/MovieFileSearcher.h
- src/ui/main/FileScannerDialog.cpp
This change reworks the file searcher (again).  It now runs in another
thread, or rather: The jobs for each directory run in another thread.
We had to make the database access work with multiple threads and fix
some other multithreading issues.  But this was worth the cost because
now MediaElch no longer freezes for reloading movies from slow disks.
It also makes it possible to remove calls to
`QApplication::processEvents()` that previously were the causes for
crashes.
-------------
Fix #1326
> [MovieFileSearcher] Run searcher in another thread

- CHANGELOG.md
- CMakeLists.txt
- src/export/ExportTemplateLoader.cpp
- third_party/CMakeLists.txt
This makes it possible to use MediaElch with QuaZip 1.1
Tested with openSUSE Tumbleweed and QuaZip 1.1. Also tested on Ubuntu 18.04 with QuaZip 0.9. Builds using the git submodule still work as well. QMake build works as well.
Fix https://github.com/Komet/MediaElch/issues/1339
> [QuaZip] Use header include path "quazip/" instead of "quazip5/"

- CHANGELOG.md
- src/export/CsvExport.cpp
To avoid the possibility of CSV injection, prepend certain fields with
an apostrophe according to OWASP recommendations
- https://owasp.org/www-community/attacks/CSV_Injection
Fix #1338
> [CSV Export] Escape characters according to OWASP recommendation

- MediaElch.pro
- src/globals/Meta.h
- src/globals/TrailerDialog.cpp
- src/globals/TrailerDialog.h
- src/ui/export/CsvExportDialog.h
- src/ui/tv_show/TvTunesDialog.cpp
- src/ui/tv_show/TvTunesDialog.h
This is another step towards support for Qt 6.2.
What's left:
- Fix QuaZip (currently only support Qt5)
Note that I still got linker errors on my machine due to some OpenGL
issues.  But Qt 6.2 is still alpha, so that's not a big issue (yet).
> [Qt] Improve MediaElch to (nearly) support Qt6

- CHANGELOG.md
- CMakeLists.txt
- MediaElch.pro
- src/CMakeLists.txt
- src/export/CMakeLists.txt
- src/movies/MovieFilesOrganizer.cpp
- src/tv_shows/CMakeLists.txt
- src/ui/main/MyIconFont.cpp
- src/ui/settings/GlobalSettingsWidget.cpp
- third_party/CMakeLists.txt
- third_party/quazip.pri
Update submodule to QuaZip 1.1.  Furthermore, apply fixes so that we
can also work with QuaZip 1.1 for Qt6.
> [QuaZip] Update submodule to QuaZip 1.1 and add basic support for Qt6

- .ci/docker/Dockerfile.ci.linux
- MediaElch.pro
- src/data/Actor.h
- src/data/Rating.h
- src/file/Path.h
- src/globals/Meta.h
- src/ui/main/AboutDialog.cpp
- src/ui/main/MainWindow.cpp
- src/ui/settings/GlobalSettingsWidget.cpp
I added usage of `qsizetype` about 5 months ago, to fix some warnings
for Qt6.  I tested it with Qt 5.15 but forgot to test 5.6.
Turns out `qsizetype` was introduced in Qt 5.10.
> [Qt] Fix builds for Qt < 5.10

- CHANGELOG.md
- MediaElch.pro
- src/scrapers/CMakeLists.txt
- src/scrapers/ScraperUtils.cpp
- src/scrapers/ScraperUtils.h
- src/scrapers/imdb/ImdbReferencePage.cpp
- src/scrapers/imdb/ImdbReferencePage.h
- src/scrapers/music/AllMusic.cpp
- src/scrapers/music/AllMusic.h
- src/scrapers/music/Discogs.cpp
- src/scrapers/music/Discogs.h
- src/scrapers/music/MusicBrainz.cpp
- src/scrapers/music/MusicBrainz.h
- src/scrapers/tv_show/imdb/ImdbTvEpisodeParser.cpp
- src/scrapers/tv_show/imdb/ImdbTvShowParser.cpp
- src/scrapers/tv_show/imdb/ImdbTvShowParser.h
This commit fixes some music scrapers where the contents, e.g, review
and biography, were not correctly decoded and still contained HTML
entities such as `&amp;`.
> [Music Scrapers] Correctly decode / remove HTML entities / tags

- CMakeLists.txt
- cmake/MediaElchMisc.cmake
- src/CMakeLists.txt
This commit refactors our main `CMakeLists.txt` file and adds a first
version of macOS bundles for MediaElch.
> [CMake] Refactor: Add support for MediaElch.app on macOS

- src/export/ExportTemplate.cpp
- src/export/ExportTemplate.h
- src/export/ExportTemplateLoader.cpp
- src/export/ExportTemplateLoader.h
- src/ui/settings/ExportTemplateWidget.cpp
- src/ui/settings/ExportTemplateWidget.ui
- test/integration/export/testSimpleExport.cpp
- test/unit/CMakeLists.txt
- test/unit/export/test.ExportTemplateLoader.cpp
This commit makes it possible to write multiple `<author>` tags in
an export theme's `metadata.xml`.  Furthermore, tests were added.
----------------
Fix #1364
> [ExportTheme] Allow multiple `<author>` tags in `metadata.xml`

- .github/workflows/superlinter.yml
- CHANGELOG.md
- CMakePresets.json
- src/scrapers/tv_show/tmdb/TmdbTvShowParser.h
- src/ui/concerts/ConcertFilesWidget.cpp
- src/ui/concerts/ConcertInfoWidget.cpp
- src/ui/concerts/ConcertInfoWidget.h
- src/ui/concerts/ConcertStreamDetailsWidget.cpp
- src/ui/concerts/ConcertStreamDetailsWidget.h
- src/ui/concerts/ConcertWidget.cpp
- src/ui/concerts/ConcertWidget.h
Fix  #1335
------------------
There was a use-after-free bug in MediaElch where it would crash if a
concert was selected that has ratings and then "reload" was pressed.
Why did it crash? Because the old concert was deleted, but we still held
the reference to it in the info widget. While clear() was called, we did
not reset the reference.
> [Concert] Fix use-after-free when reloading concerts

- CHANGELOG.md
- src/concerts/ConcertController.cpp
- src/concerts/ConcertController.h
- src/data/MediaInfoFile.cpp
- src/data/MediaInfoFile.h
- src/data/StreamDetails.cpp
- src/data/StreamDetails.h
- src/image/ImageCapture.cpp
- src/movies/MovieController.cpp
- src/movies/MovieController.h
- src/tv_shows/TvShowEpisode.cpp
- src/tv_shows/TvShowEpisode.h
- src/ui/concerts/ConcertFilesWidget.cpp
- src/ui/concerts/ConcertStreamDetailsWidget.cpp
- src/ui/concerts/ConcertStreamDetailsWidget.h
- src/ui/concerts/ConcertStreamDetailsWidget.ui
- src/ui/concerts/ConcertWidget.cpp
- src/ui/imports/ImportDialog.cpp
- src/ui/imports/MakeMkvDialog.cpp
- src/ui/movies/MovieFilesWidget.cpp
- src/ui/movies/MovieWidget.cpp
- src/ui/movies/MovieWidget.h
- src/ui/movies/MovieWidget.ui
- src/ui/small_widgets/LoadingStreamDetails.cpp
- src/ui/tv_show/TvShowFilesWidget.cpp
- src/ui/tv_show/TvShowWidgetEpisode.cpp
- src/ui/tv_show/TvShowWidgetEpisode.h
- src/ui/tv_show/TvShowWidgetEpisode.ui
> [StreamDetails] Don't override details if MediaInfoDll is not found

- CHANGELOG.md
- src/globals/DownloadManager.cpp
- src/movies/MovieController.cpp
MediaElch would crash if I downloaded more than 10 or 20 movies at once.
This happened because running downloads were not aborted properly.
I still need to investigate why this even happens: There may be a
mismatch between movies in the Image provider, i.e. the callback for
the wrong movie is called.
---------------
Fix #1408
> [DownloadManager] Correctly abort downloads to avoid crash

- CHANGELOG.md
- src/ui/small_widgets/TvShowTreeView.cpp
This commit fixes the white background when a TV show / season /
episode was selected.
There is still a TODO open, see inline comments of the diff.
-------------------
Before:
After:
-------------------
Fix  #1412
> [UI TvShow] Fix white background on selection

- src/image/ImageCapture.cpp
ffmpeg -vframes switch is outdated and will likely stop working some time in the future
See https://ffmpeg.org/ffmpeg.html
"-vframes number (output) - Set the number of video frames to output. This is an obsolete alias for -frames:v, which you should use instead."
I found this by accident as I was having a look at the code to grab screenshots because I was trying to figure out whether I could make a mini ffmpeg build for a docker image. I didn't get far with that pursuit, but every example I found about grabbing frames had -frames:v instead of -vframes, so I looked at the documentation and found the above page.
You might want to check that it still works with this change as I have not built it with this change, but it seems simple enough.
> Change outdated ffmpeg switch

- docs/advancedsettings.xml
- src/settings/AdvancedSettings.cpp
Sourced from here: https://en.wikipedia.org/wiki/Article_(grammar)#Tables 
Going over the list and including the rest (without major coflicts) is left as an exercise to the reader.
This is *much* more complex than this simple feature can handle, but these should cover [~2 billion people](https://en.wikipedia.org/wiki/List_of_languages_by_total_number_of_speakers).
> Add more languages to the sort tokens

- CHANGELOG.md
- src/globals/DownloadManager.cpp
- src/globals/DownloadManager.h
- src/globals/DownloadManagerElement.cpp
- src/globals/DownloadManagerElement.h
- src/movies/MovieController.cpp
- src/movies/MovieController.h
- src/scrapers/image/FanartTv.cpp
- src/ui/media_centers/KodiSync.cpp
- src/ui/movies/MovieMultiScrapeDialog.cpp
- src/ui/movies/MovieMultiScrapeDialog.h
- src/ui/movies/MovieWidget.cpp
This commit fixes some issues with the download manager.  Some signals
were emitted twice, the logging for running downloads was improved and
overall movie-image mismatches were fixed.
--------------
Fix  #1409
> [Movies] Fix double loading images; incorrect image matching

- CHANGELOG.md
- src/tv_shows/TvShowFileSearcher.cpp
- test/unit/tv_shows/testTvShowFileSearcher.cpp
This commit fixes our episode number matching.  Because we used a
capturing group instead of a positive lookahead, `S01E01E02E03` was
not correctly identified, because one `E` was matched for the previous
episode number.
------------
Fix #1429
> [Episodes] Match multi-episode names such as `S01E01E02E03`

- CHANGELOG.md
- src/movies/Movie.cpp
- src/movies/Movie.h
- src/movies/MovieModel.cpp
Previous to this commit, the UI column "subtitles" was only green if
there were subtitles embedded in stream details.
This is no longer the case. We now also check if the movie has external
subtitles, such as `*.srt` files.
> [UI] Movie also has subtitles if there are external subtitles

- CHANGELOG.md
- src/concerts/Concert.cpp
- src/concerts/Concert.h
- src/renamer/MovieRenamer.cpp
- src/renamer/RenamerDialog.cpp
- src/renamer/RenamerDialog.ui
- src/renamer/RenamerPlaceholders.ui
- src/ui/settings/ConcertSettingsWidget.cpp
- src/ui/settings/ConcertSettingsWidget.ui
- src/ui/settings/MovieSettingsWidget.ui
- src/ui/settings/TvShowSettingsWidget.cpp
- src/ui/settings/TvShowSettingsWidget.ui
- src/ui/small_widgets/PlaceholderLineEdit.cpp
- src/ui/small_widgets/PlaceholderLineEdit.h
This commit makes it possible to set default values for certain text
fields such as in the RenamerDialog.  This allows users to switch
back to defaults if they accidentally edited the box.
This is done for Renamer line edits.  Only few examples were edited by
default.
-------------
Fix  #657
> [UI] Use QComboBox for PlaceholderLineEdit to provide default

- CHANGELOG.md
- src/network/NetworkManager.cpp
- src/network/NetworkManager.h
- src/settings/NetworkSettings.cpp
- src/settings/NetworkSettings.h
- src/tv_shows/TvShowEpisode.cpp
- src/ui/main/MainWindow.cpp
- src/ui/media_centers/KodiSync.cpp
- src/ui/media_centers/KodiSync.h
- src/ui/settings/NetworkSettingsWidget.cpp
- src/ui/settings/NetworkSettingsWidget.ui
Default: Proxy disabled for Kodi, since it's most likely in the local
network.
------------
Fix  #1430
> [NetworkSettings/KodiSync] Allow disabling proxy for Kodi sync

- src/ui/settings/ConcertSettingsWidget.cpp
- src/ui/settings/MovieSettingsWidget.cpp
- src/ui/settings/MusicSettingsWidget.cpp
- src/ui/settings/SettingsWindow.cpp
- src/ui/settings/TvShowSettingsWidget.cpp
- src/ui/small_widgets/PlaceholderLineEdit.cpp
This is a follow up to commit https://github.com/bugwelle/MediaElch/commit/b15d5d2752745ce60f36c3fd87b4b00503f3b6b0.
Because the underlying type changed from QLineEdit to QComboBox,
`findChildren<QLineEdit*>()` failed.  That was an oversight back then.
This effects all settings of MediaElch and is a major bug!
Fix #1448
> [Settings] Fix storing values from QComboBox

- CHANGELOG.md
- src/media_centers/kodi/ConcertXmlWriter.cpp
- src/media_centers/kodi/EpisodeXmlWriter.cpp
- src/media_centers/kodi/MovieXmlWriter.cpp
Kodi can't handle empty `uniqueid`s.
> [Kodi XML] Only write unique id if there is one

- CHANGELOG.md
- src/scrapers/tmdb/TmdbApi.cpp
- src/scrapers/tv_show/tmdb/TmdbTvShowParser.cpp
- test/scrapers/tmdbtv/testTmdbTvShowLoader.cpp
Hello,
please excuse if this PR should have been a discussion issue first, I am hoping this way it is easiest to see what I am trying to achieve.
I noticed that an actor was missing from the metadata of a tv show scraped by MediaElch using Tmdb.
The show in this case was one of the main characters in Stargate SG1 (https://www.themoviedb.org/tv/4629-stargate-sg-1).
On the web "Richard Dean Anderson - Jack O'Neill" is listed first, but he was missing from the saved metadata.
An investigation showed that the "credits" API call defaults to the cast of the last season of a show. Some time later an "aggregate_credits" call has been added that returns the full cast more alike it is shown on the website.
I would like to switch to this call as to me it seems unexpected to be limited to the last …
> [TmdbApi] Use "aggregate_credits" call for shows, Prevent invalid actor profile URLs

- src/network/NetworkManager.cpp
- src/network/NetworkManager.h
- src/ui/media_centers/KodiSync.cpp
If a proxy was disabled for syncing Kodi, and then enabled again,
subsequent kodi-sync steps still did not use the proxy.
-----------------
Fix #1446
> [KodiSync] Explicitly use default proxy if enabled in settings

- src/network/NetworkManager.cpp
- src/ui/media_centers/KodiSync.cpp
- src/ui/media_centers/KodiSync.ui
For #1446
-----
The documentation of Qt is clear.  I thought that `DefaultProxy` uses,
well, the default proxy, i.e. applicationProxy().  That seems not to be
the case.
> [NetworkManager] Explicitly use applicationProxy() in enabledefaultProxy()

- CHANGELOG.md
- src/ui/image/ImageDialog.cpp
This (hopefully) fixes a use after free bug, where `m_currentDownloadReply->abort()` was called after `m_currentDownloadReply` was deleted.  This went undetected, because `deleteLater()` does not clear the pointer (only if `QPointer<>` were to be used).
Maybe we should use QPointer here, but that's for another commit.
------------
For https://github.com/Komet/MediaElch/issues/1475
> fix(ImageDialog): Clear pointer after call to deleteLater()

- src/file_search/ConcertFileSearcher.cpp
- src/file_search/MusicFileSearcher.cpp
- src/file_search/TvShowFileSearcher.cpp
- src/file_search/movie/MovieDirScan.cpp
- src/file_search/movie/MovieDirectorySearcher.cpp
- src/file_search/movie/MovieFileSearcher.cpp
- src/import/DownloadFileSearcher.cpp
- src/media/FileFilter.cpp
- src/media/FileFilter.h
- src/renamer/ConcertRenamer.cpp
- src/renamer/EpisodeRenamer.cpp
- src/settings/AdvancedSettings.cpp
- src/settings/AdvancedSettings.h
- src/settings/AdvancedSettingsXmlReader.cpp
The FileFilter class was only used for filtering directories using QDir's filter functionality.  That's only used as a positive glob filter.  But we also have file name and directory name filters.  Those are now also part of it.  Furthermore, rename some methods to make it more clear what they are, e.g. "filter" is too generic.  Is it a positive or negative filter? What does it filter?
> refactor: Move different file filters into FileFilter class

- CHANGELOG.md
- src/main.cpp
- src/ui/UiUtils.cpp
- src/ui/main/MyIconFont.cpp
- src/ui/small_widgets/Badge.cpp
By settings the font size explicitly to what it already is, we get rid
of Windows scaling issues on HighDPI screens with scaling > 100%.
Fixes #1502
> fix(UI): Explicitly set default font size to what it already is

- CHANGELOG.md
- src/utils/Meta.cpp
Signals "allMovieDownloadsFinished", etc. are queued in some widgets. Because of that, the meta types "TvShow*", etc. need to be registered. That was not yet the case and the "Downloading Images..." dialog was never removed.
----
Fix  #1507
> fix(DownloadManager): Register meta types for `Movie`/etc for signals

- src/file_search/movie/MovieDirectorySearcher.cpp
- src/file_search/movie/MovieFileSearcher.cpp
A recently regularly reported bug was that the "loading files" dialog did not disappear and movies were not loaded.  Few even reported crashes.  I was not able to reproduce this issue for a long time, so didn't get to debug it.
The reason the dialog was stuck was that the `MovieLoader*` object was destroyed in its thread before it was used in the main thread. That happened for two reasons: `MovieLoader::finished` was connected to `QThread::quit` which in turn deleted the thread.  Deleting the thread also deleted the `MovieLoader` object.
Secondly, calling `job->deleteLater()` from the main thread enqueues the object for deletion in the worker thread.  Using `job` after that was never safe.
The coding got that way because calling `deleteLater()` early is a pattern I use: The object gets …
> fix(FileLoader): Fix use-after-free in `onDirectoryLoaded(MovieLoader*)`

- src/utils/Meta.h
Fixes #1511
32bit builds don't have 64-bit types for Qt functions such as `count()`, they still use 32bit return values.  Such a call to `safe_int_cast<int>(a.count())` fails on 32-bit systems.
We don't need the check anyway.  It was a sanity check while I upgraded from Qt5 to Qt6.
> fix(Meta): Don't do 64-bit related checks for 32-bit builds

- CHANGELOG.md
- src/media_center/kodi/TvShowXmlReader.cpp
- src/media_center/kodi/TvShowXmlWriter.cpp
- test/resources/show/kodi_v20_show_Game_of_Thrones.nfo
- test/resources/show/kodi_v20_show_Game_of_Thrones_TvDb_episode_guide.nfo
- test/resources/show/kodi_v20_show_Torchwood.nfo
- test/resources/show/kodi_v20_show_all.nfo
- test/resources/show/kodi_v20_show_empty.nfo
Kodi v19.5 and later use a different episodeguide format.  Use that as well.  Since we don't need to read the episodeguide (since we already have all unique IDs), we can simply write what we already know: A map of IDs in JSON format.
Furthermore, remove `year` for Kodi v19 and later, because in v20, only `premiered` must be used.
Fixes #1519
> fix(TV show): Adapt `<episodeguide>` to Kodi v20 changes

- CHANGELOG.md
- docs/advancedsettings.xml
- src/main.cpp
- src/settings/AdvancedSettings.cpp
- src/settings/AdvancedSettings.h
- src/settings/AdvancedSettingsXmlReader.cpp
- src/ui/dark.css
- src/ui/palette_dark.json
- ui.qrc
For #761 
This commit adds an experimental dark mode for MediaElch's
_main window_.  It can only be set through `advancedsettings.xml` and
will be made into a proper settings option in future releases.
-------------
Screenshot:
> feat(UI): Add experimental dark mode for main window

- CHANGELOG.md
- MediaElch.pro
- src/ui/small_widgets/WebImageLabel.h
- src/ui/tv_show/CMakeLists.txt
- src/ui/tv_show/TvShowSearch.cpp
- src/ui/tv_show/TvShowSearch.ui
- src/ui/tv_show/TvShowSearchWidget.cpp
- src/ui/tv_show/TvShowSearchWidget.h
- src/ui/tv_show/TvShowSearchWidget.ui
- src/ui/tv_show/TvShowWidgetTvShow.cpp
- src/ui/tv_show/search_dialog/TvShowScrapePreview.cpp
- src/ui/tv_show/search_dialog/TvShowScrapePreview.h
- src/ui/tv_show/search_dialog/TvShowScrapePreview.ui
This commit adds a preview widget to the TV show search widget.
This makes it easier to select the correct TV show, especially if
there are multiple results that are quite similar.
__Before__
__After__:
> feat(TvShow Search): Add preview of poster/overview to search dialog

- scripts/create_themes_from_palettes.py
- src/model/TvShowModel.cpp
- src/model/TvShowModel.h
- src/ui/base.css
- src/ui/dark.css
- src/ui/light.css
- src/ui/palette_dark.json
- src/ui/small_widgets/TvShowTreeView.cpp
- src/ui/small_widgets/TvShowTreeView.h
Instead of hard-coding the background color, use the stylesheet's background definition.  We had a workaround for Windows, which seems not to be needed anymore.  Still needs to be tested on Windows.
__Light__
<table><tr><th>Before<th><th>After<th></tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/1667306/210070612-0ba09c2c-a897-4427-bbc8-6137d0e726eb.png"/><td><td><img src="https://user-images.githubusercontent.com/1667306/210070617-25e3f6d3-8c13-4b3d-8542-7a22180095ad.png"/><td>
</tr></table>
__Dark__
<table><tr><th>Before<th><th>After<th></tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/1667306/210070615-5936922e-91fd-471a-9b96-545c6fbae6c1.png"/><td>
<td><img src="https://user-images.githubusercontent.com/1667306/210070618-40f373ef-e6dd-4714-b403-ed1dc26 …
> fix(UI): TV show file tree: Use stylesheet's selection background

- CHANGELOG.md
- src/data/TmdbId.cpp
- src/data/TmdbId.h
- src/data/TvDbId.cpp
- src/scrapers/concert/ConcertSearchJob.cpp
- src/scrapers/movie/MovieSearchJob.cpp
- src/scrapers/tmdb/TmdbApi.cpp
- src/scrapers/tv_show/ShowSearchJob.cpp
If a TV show title looked like a TMDb id (i.e. only numbers such as 1899 or 1923), we assumed it indeed was an ID and not a search query.
--------------
Fix #1527
> fix(TMDb search): Don't assume 1923 or other numbers are a TMDb ids

- .ci/macOS/build_macOS_release_Qt6.sh
- .ci/macOS/package_macOS_Qt6.sh
- CHANGELOG.md
- MediaElch.plist
- MediaElch.pro
- docs/contributing/guides/build-qt6-with-tsan.md
- src/main.cpp
- src/settings/AdvancedSettings.cpp
- src/settings/AdvancedSettings.h
- src/settings/AdvancedSettingsXmlReader.cpp
- src/settings/Settings.cpp
- src/settings/Settings.h
- src/ui/CMakeLists.txt
- src/ui/MacUiUtilities.h
- src/ui/MacUiUtilities.mm
- src/ui/light.css
- src/ui/palette_light.json
- src/ui/settings/GlobalSettingsWidget.cpp
- src/ui/settings/GlobalSettingsWidget.ui
- test/scrapers/tmdbtv/testTmdbTvShowSearch.cpp
This commit adds a combobox to MediaElch's global settings.  The new
"theme" setting is used to determine MediaElch's main window theme.
On macOS, "auto" can be used to determine the theme automatically.
On other systems, we (currently) default to "light".
This commit also reverts https://github.com/Komet/MediaElch/commit/e5d2a63bdf8f900a301a5a31ff969ec007689470
which disabled dark mode for MediaElch.
-------------
For #761
> feat(UI theme): Add UI theme settings to global settings dialog

- CHANGELOG.md
- scripts/library/movies_en.txt
- src/renamer/MovieRenamer.cpp
- src/ui/renamer/RenamerDialog.cpp
- src/ui/renamer/RenamerPlaceholders.ui
It is now possible to add TMDb ID as a placeholder for movie files and directories.
Fix #1542
> feat(Renamer): Add TMDb ID as a placeholder for movies to the renamer

- .tx/config
- CHANGELOG.md
- data/i18n/MediaElch_ar.ts
- data/i18n/MediaElch_bg.ts
- data/i18n/MediaElch_cs_CZ.ts
- data/i18n/MediaElch_da.ts
- data/i18n/MediaElch_de.ts
- data/i18n/MediaElch_en.ts
- data/i18n/MediaElch_es_ES.ts
- data/i18n/MediaElch_fi.ts
- data/i18n/MediaElch_fr.ts
- data/i18n/MediaElch_he_IL.ts
- data/i18n/MediaElch_it.ts
- data/i18n/MediaElch_ja.ts
- data/i18n/MediaElch_ko.ts
- data/i18n/MediaElch_ku_IQ.ts
- data/i18n/MediaElch_lt_LT.ts
- data/i18n/MediaElch_my.ts
- data/i18n/MediaElch_nl_NL.ts
- data/i18n/MediaElch_no.ts
- data/i18n/MediaElch_pl.ts
- data/i18n/MediaElch_pt_BR.ts
- data/i18n/MediaElch_ru.ts
- data/i18n/MediaElch_sv.ts
- data/i18n/MediaElch_tr_TR.ts
- data/i18n/MediaElch_zh_CN.ts
- src/globals/Helper.cpp
- src/globals/Helper.h
- src/model/MovieModel.cpp
Fix #1545
------
Color labels were for light theme only.  That made it nearly unreadable
in dark theme.
@ironhussar What do you think?
> fix(UI): Adapt color labels for dark theme

- CHANGELOG.md
- src/ui/small_widgets/LanguageCombo.cpp
- src/ui/small_widgets/LanguageCombo.h
The language list seemed to be sorted arbitrary in everything except English.  Now it's sorted.
Fix #1560
> fix(UI): Sort the translated language names in LanguageCombo class

- CHANGELOG.md
- src/CMakeLists.txt
- src/ui/settings/CustomTvScraperSettingsWidget.cpp
- src/ui/settings/ScraperSettingsWidget.cpp
The list of custom movie scraper details was not sorted, because we used `QSet` and not an array/vector.  Move to `QVector` but assert that we don't list duplicates via assertions in debug mode.
> fix(UI): Sort custom movie scraper details

- CHANGELOG.md
- src/ui/base.css
- src/ui/dark.css
- src/ui/light.css
- src/ui/small_widgets/MusicTreeView.cpp
- src/ui/small_widgets/TvShowTreeView.cpp
It seems due to strange behavior of Qt, settings the background color for selections via `selection-background-color` only affects `PE_PanelItemViewRow` on macOS, whereas `PE_PanelItemViewItem` is affected by `background-color` and `::item:selected` on Windows/Linux.
See https://stackoverflow.com/a/34646515/1603627
This is strange. I don't get why this is the case, yet.
Fix #1569
> fix(UI): Selection background color of shows/episodes and artists/albums

- src/network/NetworkManager.cpp
- src/network/NetworkManager.h
- src/network/WebsiteCache.cpp
- src/network/WebsiteCache.h
- src/scrapers/imdb/ImdbApi.cpp
- src/scrapers/imdb/ImdbApi.h
- src/scrapers/movie/adultdvdempire/AdultDvdEmpireApi.cpp
- src/scrapers/movie/adultdvdempire/AdultDvdEmpireApi.h
- src/scrapers/movie/aebn/AebnApi.cpp
- src/scrapers/movie/aebn/AebnApi.h
- src/scrapers/movie/hotmovies/HotMoviesApi.cpp
- src/scrapers/movie/hotmovies/HotMoviesApi.h
- src/scrapers/movie/videobuster/VideoBusterApi.cpp
- src/scrapers/movie/videobuster/VideoBusterApi.h
- src/scrapers/music/AllMusic.h
- src/scrapers/music/MusicBrainz.cpp
- src/scrapers/music/MusicBrainz.h
- src/scrapers/music/TheAudioDb.cpp
- src/scrapers/music/TheAudioDb.h
- src/scrapers/tmdb/TmdbApi.cpp
- src/scrapers/tmdb/TmdbApi.h
- src/scrapers/tv_show/thetvdb/TheTvDbApi.cpp
- src/scrapers/tv_show/thetvdb/TheTvDbApi.h
- src/scrapers/tv_show/tvmaze/TvMazeApi.cpp
- src/scrapers/tv_show/tvmaze/TvMazeApi.h
The network manager now has a website cache.  Most users of
NetworkManager has a WebsiteCache themselves.  In the future, they
should probably be combined somehow.
-----
In preparation for #1578
> refactor(network): Move website cache to NetworkManager

- CHANGELOG.md
- src/ui/settings/GlobalSettingsWidget.cpp
For some reason, on the latest macOS versions (with Qt 5.15.2), the settings window disappears when a directory was selected.  The main window is put in front of the settings window.  That is bad, because we currently do not have a "Windows" bar item where users can easily switch between windows.
------
Fix #1577
TODO:
> fix(UI): Move settings window to top after selecting directory (macOS)

- CHANGELOG.md
- src/data/movie/MovieController.cpp
- src/scrapers/movie/MovieMerger.cpp
- src/scrapers/movie/MovieMerger.h
- src/scrapers/movie/custom/CustomMovieScrapeJob.cpp
- test/helpers/CMakeLists.txt
- test/helpers/fake_data.cpp
- test/helpers/fake_data.h
- test/unit/CMakeLists.txt
- test/unit/scrapers/custom_movie_scraper/StubMovieScraper.cpp
- test/unit/scrapers/testMovieMerger.cpp
After the movie scraper refactoring, it was forgotten to copy the _original_ title if needed.  The setting "ignore duplicate original title" needs to be respected as well.
----
Fix #1601
> fix(MovieScraper): Correctly copy original title if required

- CHANGELOG.md
- src/scrapers/music/MusicBrainz.cpp
It appears as if MusicBrainz can't handle search requests with a Content-Type header anymore, at least not XML.
Without the header, requests work as expected.
Fix #1597
> fix(MusicBrainz): Don't set Content-Type header in GET request

- CHANGELOG.md
- src/data/movie/MovieController.cpp
This was forgotten in the movie scraper rewrite.  The coding may be verbose, but it will fix a feature that is commonly used by our users.
---
Fix #1598
> fix(CustomMovieScraper): Load images from fanart.tv if requested

- CHANGELOG.md
- MediaElch.pro
- src/ui/movies/CMakeLists.txt
- src/ui/movies/MoviePreviewAdapter.cpp
- src/ui/movies/MoviePreviewAdapter.h
- src/ui/movies/MovieSearchWidget.cpp
- src/ui/movies/MovieSearchWidget.h
- src/ui/movies/MovieSearchWidget.ui
- src/ui/small_widgets/ScrapePreview.h
This commit adds a preview widget to the Movie search widget. This makes it easier to select the correct movie, especially if there are multiple results that are quite similar.
> feat(Movie Search): Add preview of poster/overview to search dialog

- CHANGELOG.md
- scripts/library/tvshows_en/Buffy/Season_01.txt
- src/scrapers/tv_show/imdb/ImdbTvEpisodeParser.cpp
- test/resources/scrapers/imdbtv/Buffy-S01E00-minimal-details.ref.txt
- test/resources/scrapers/imdbtv/Buffy-S01E01-minimal-details.ref.txt
- test/resources/scrapers/imdbtv/The-Simpsons-tt0096697-minimal-details.ref.txt
- test/scrapers/imdbtv/testImdbTvEpisodeLoader.cpp
Episode "00" (e.g. pilot episodes) increased IMDbs episode URL counter. That means, we were always off-by-one and episode 00 could not be scraped.  This is now fixed and we have tests to ensure that this does not happen again.
---
Fix #1610
> fix(IMDb TV): Fix scraping of episodes if there is an episode 00

- CHANGELOG.md
- docs/advancedsettings.xml
- src/settings/AdvancedSettingsXmlReader.cpp
- test/unit/scrapers/testImdbTvEpisodeParser.cpp
- test/unit/settings/testAdvancedSettings.cpp
Fix #1613
---
Due to Copy&Paste, we used `m_settings.m_sortTokens.clear();` when
reading `exclude`.
> fix(AdvancedSettings): Don't clear sort tokens when reading `<exclude>`

- src/scrapers/imdb/ImdbApi.h
- src/scrapers/tv_show/thetvdb/TheTvDbApi.h
- src/ui/concerts/ConcertWidget.cpp
- src/ui/image/ImageDialog.cpp
- src/ui/image/ImageDialog.h
- src/ui/image/ImageDialog.ui
- src/ui/import/DownloadsWidget.cpp
- src/ui/movie_sets/SetsWidget.cpp
- src/ui/movies/CertificationWidget.cpp
- src/ui/movies/GenreWidget.cpp
- src/ui/movies/MovieFilesWidget.cpp
- src/ui/movies/MovieWidget.cpp
- src/ui/music/MusicFilesWidget.cpp
- src/ui/music/MusicWidgetAlbum.cpp
- src/ui/music/MusicWidgetArtist.cpp
- src/ui/tv_show/TvShowFilesWidget.cpp
- src/ui/tv_show/TvShowWidgetEpisode.cpp
- src/ui/tv_show/TvShowWidgetSeason.cpp
- src/ui/tv_show/TvShowWidgetTvShow.cpp
[](https://github.com/Komet/MediaElch/commit/cecaf56b723e806eec41ea1b2ccd53a9ef679f33)
The image dialog window is resized during `exec()`.  That, however,
does not immediately resize the image table.  That happens later, as
children's size is based on the parents size.  This has the effect,
that the column-calculation is based on a lower size than is being shown
to the user.  By postponing the calculation to the next event loop
iteration, we get a proper number of columns.
_Before_
_After_
Fixes #1620
> fix(UI): Fix image column count in image dialogs on first appearance

- CHANGELOG.md
- docs/advancedsettings.xml
- src/data/Filter.cpp
- src/data/TmdbId.cpp
- src/data/TmdbId.h
- src/model/music/MusicModel.cpp
- src/ui/base.css
- src/ui/dark.css
- src/ui/light.css
- src/ui/palette_dark.json
- src/ui/palette_light.json
- src/ui/small_widgets/FilterWidget.cpp
- src/ui/small_widgets/FilterWidget.h
- src/ui/small_widgets/MusicTreeView.cpp
- src/ui/small_widgets/MusicTreeView.h
- src/ui/small_widgets/TvShowTreeView.cpp
- src/ui/small_widgets/TvShowTreeView.h
- test/unit/data/testTmdbId.cpp
Fix #1629
<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
> fix(UI): Fix background of filter dropdown menu in dark theme

- CHANGELOG.md
- src/ui/image/ImageDialog.cpp
- src/ui/image/ImageDialog.h
The image dialog, when downloading images, now sorts the list of images by preferred language before downloading if available.
---
Fix #1619
> feat(ImageDialog): Sort images (e.g. fanart.tv) by preferred locale

- CHANGELOG.md
- src/scrapers/music/UniversalMusicScraper.cpp
- test/resources/scrapers/universalmusicscraper/bad-habit.ref.txt
- test/resources/scrapers/universalmusicscraper/metallica.ref.txt
- test/scrapers/universalmusicscraper/testUniversalMusicScraper.cpp
If MusicBrainz has no Discogs link, don't wait for it to load - it will never happen.
> fix(Music): Don't require Discogs to load if there is no link

- src/data/movie/Movie.cpp
Tags are set the same way as genres, countries and studios, but didn't have duplication problem because there was a check if the tag is already set for the movie. I added the same check to genre, country and studio. Probably not necessary, but I also added test for empty argument into `Movie::addTag`, since it was done in the other functions.
It probably makes more sense to use `QMap` instead of `QStringList` for tags, genres, countries, and studios. It would make checking for existing items faster, and when iterating `QMap`, the items will be sorted by keys. But I'm not sure how much it would affect the performance, and it would probably require a lot of changes.
> Fix #1635 Duplicate movie Genres, Countries and Studio labels when scrapping

- CHANGELOG.md
- src/ui/tv_show/TvShowWidgetEpisode.cpp
- src/ui/tv_show/TvShowWidgetEpisode.ui
- src/ui/tv_show/TvShowWidgetTvShow.cpp
- src/ui/tv_show/TvShowWidgetTvShow.ui
For TV shows and episodes, add a marker "missing" to indicate that the "first aired" date is missing.  Qt does not have a good way to mark the QDateWidget "invalid".  It requires a date that it can show.
And the defaults are awful: 2000-01-01 is the default. We simply show the _current_ date with a label "missing" in case the date is invalid.
----
Fix  #1663
> fix(UI): Add "missing" label to "first aired" field if it is the default

- CHANGELOG.md
- src/ui/base.css
- src/ui/dark.css
- src/ui/light.css
- src/ui/main/MainWindow.cpp
- src/ui/main/MainWindow.ui
- src/ui/main/MyIconFont.cpp
- src/ui/main/MyIconFont.h
The numbers in bubbles were not device-pixel-ratio independent.  They were wrongly sized on some systems.  Furthermore, increase the icon size for Linux and macOS of the left navigation bar.
For #1662
> fix(UI): Correctly scale icons in left navigation bar

- .ci/linux/package_linux_appimage.sh
- CHANGELOG.md
For whatever reason, the SVG plugin was not deployed by linuxdeploy (via https://github.com/linuxdeploy/linuxdeploy-plugin-qt ).
Adding it explicitly helped. As a side-effect, the icons in the navigation bar are finally displayed correctly.
---
Fix #1662
> ci(AppImage): Always include SVG image plugin

- src/data/tv_show/TvShow.cpp
- src/scrapers/tmdb/TmdbApi.cpp
- src/scrapers/tmdb/TmdbApi.h
- src/scrapers/tv_show/tmdb/TmdbTvEpisodeParser.cpp
- src/scrapers/tv_show/tmdb/TmdbTvSeasonParser.cpp
- src/scrapers/tv_show/tmdb/TmdbTvSeasonParser.h
- src/scrapers/tv_show/tmdb/TmdbTvSeasonScrapeJob.cpp
- src/scrapers/tv_show/tmdb/TmdbTvSeasonScrapeJob.h
- test/resources/scrapers/tmdbtv/The-Simpsons-S12.ref.txt
- test/resources/scrapers/tmdbtv/The-Simpsons-all-seasons-S12-E19.ref.txt
TMDb does not send the same actors for each episodes when requesting a season. Instead, there are the same actors for the whole season and then guest stars for each individual episode.
Store all actors of a season in each single episode as well.
---
Fix #1676
Note that actor _images_ are not loaded, yet. That needs a lot of refactoring which I don't have time at the moment. 
Background: The _widget_ for some reason loads images.
> fix(TMDB): Fix actors scraping for season loading (bulk episodes)

- src/ui/tv_show/TvShowMultiScrapeDialog.cpp
If `Update only TV shows/episodes which have an ID` is selected and a show does not have an ID, we displayed `Skipping show "%1" because it does not have a valid ID.`, i.e. without the text replacement.
-----
Reported in Kodi forum.
> fix(TV show multi scraper): Missing error message replacement

- src/ui/concerts/ConcertWidget.cpp
- src/ui/concerts/ConcertWidget.h
- src/ui/music/MusicWidgetArtist.cpp
- src/ui/music/MusicWidgetArtist.h
- src/ui/small_widgets/ImageGallery.cpp
- src/ui/small_widgets/ImageGallery.h
- src/ui/tv_show/TvShowWidgetTvShow.cpp
- src/ui/tv_show/TvShowWidgetTvShow.h
The image gallery supports dropping _multiple_ images by now. We should use that throughout MediaElch.
> refactor: Replace sigImageDropped by sigImagesDropped for multi-images

- src/ui/tv_show/TvShowWidgetEpisode.cpp
- src/ui/tv_show/TvShowWidgetTvShow.cpp
`Qt::SkipEmptyParts` was introduced in Qt 5.15.  I accidentally used it instead of our adapter variant.
> build: Fix build for Qt < 5.15

- .ci/docker/Dockerfile.ci.qt5.windows
- .ci/docker/Dockerfile.ci.qt6.windows
- .ci/macOS/build_macOS_release_Qt5.sh
- .ci/macOS/build_macOS_release_Qt6.sh
- .ci/macOS/check_macOS_dependencies.sh
- .ci/third_party_versions.sh
- .ci/win/build_windows_release.sh
`svn` seems to no longer work. Instead, we now use `git` to clone `ZenLib`.  Use `--depth=1` to avoid unnecessary cloning.
> ci: Fix nightly builds for Windows: use Git to clone ZenLib

- CHANGELOG.md
- src/scrapers/movie/adultdvdempire/AdultDvdEmpireScrapeJob.cpp
- src/scrapers/movie/hotmovies/HotMoviesScrapeJob.cpp
- test/resources/scrapers/ade/DVD-Magic-Mike-1745335.ref.txt
- test/resources/scrapers/ade/VOD-50-Shades-1670507.ref.txt
- test/resources/scrapers/aebn/Magic-Mike-188623.ref.txt
- test/resources/scrapers/hot-movies/Magic-Mike-292788.ref.txt
This commits allows users to also load the back cover of movies, not just the front cover.  Because MediaElch does not support multiple posters at once, we load the back cover as a backdrop, even though that is not really correct.  If the user clicks on the poster, the back cover will also appear.  The same applies to extra fanart.
Fix #1743
> feat(AEBN/HM/ADE): Also load poster back cover

- CHANGELOG.md
- src/ui/MacUiUtilities.mm
We don't support darkmode on macOS 10.x anymore.  Users can use our Qt6 build instead.
Fix #1695
> fix(macOS): Support building and running on macOS 10.13 again

- src/settings/Settings.cpp
- test/unit/file/testNameFormatter.cpp
> fix(movies): Remove `uhd` from a movie's filename when setting a title

- src/ui/concerts/ConcertInfoWidget.cpp
- src/ui/concerts/ConcertInfoWidget.ui
- src/ui/concerts/ConcertWidget.ui
- src/ui/movies/MovieWidget.cpp
- src/ui/movies/MovieWidget.ui
- src/ui/music/MusicWidgetAlbum.cpp
- src/ui/music/MusicWidgetAlbum.ui
- src/ui/music/MusicWidgetArtist.cpp
- src/ui/music/MusicWidgetArtist.ui
- src/ui/tv_show/TvShowWidgetEpisode.cpp
- src/ui/tv_show/TvShowWidgetEpisode.ui
- src/ui/tv_show/TvShowWidgetTvShow.cpp
- src/ui/tv_show/TvShowWidgetTvShow.ui
Previously, if a user copied formatted text (e.g. bold text) into text
fields, the format was copied as well, misleading the user that formatting
was possible.  However, when saving, only plain text was ever stored.
Fix #1790
> fix(UI): Use plain text fields for non-stylable text

- CHANGELOG.md
- src/scrapers/tv_show/tvmaze/TvMazeShowParser.cpp
> fix(TVMaze): Use TV shows actor's image by default, not the character's

- CHANGELOG.md
- MediaElch.pro
- src/globals/Helper.cpp
- src/globals/Helper.h
- src/media/MediaInfoFile.cpp
- src/media/MediaInfoFile.h
- src/media/StreamDetails.cpp
- src/media/StreamDetails.h
- src/media_center/KodiXml.cpp
- src/media_center/KodiXml.h
- src/media_center/kodi/ConcertXmlReader.cpp
- src/media_center/kodi/ConcertXmlReader.h
- src/ui/concerts/ConcertStreamDetailsWidget.cpp
- src/ui/concerts/ConcertStreamDetailsWidget.ui
- src/ui/movies/MovieWidget.cpp
- src/ui/movies/MovieWidget.ui
- src/ui/small_widgets/CMakeLists.txt
- src/ui/small_widgets/HdrTypeComboBox.cpp
- src/ui/small_widgets/HdrTypeComboBox.h
- src/ui/small_widgets/StereoModeComboBox.cpp
- src/ui/tv_show/TvShowWidgetEpisode.cpp
- src/ui/tv_show/TvShowWidgetEpisode.ui
Kodi's `<hdrtype>` tag is now supported. We load the HDR type via mediainfolib's `HDR_Format_Compatibility`.  Tested for HDR10 files.
Fix #1810
> feat: Add Kodi NFO `<hdrtype>`

- src/scrapers/tv_show/tvmaze/TvMazeEpisodeScrapeJob.cpp
- src/scrapers/tv_show/tvmaze/TvMazeSeasonScrapeJob.cpp
- test/resources/scrapers/tvmaze/The-Simpsons-S12E19-all-details.ref.txt
- test/resources/scrapers/tvmaze/The-Simpsons-S12E19-minimal-details.ref.txt
Follow up to b4c73e76d322dc20d61c73f373112779f09f5d16
With this change, if a user selects a single episode, more details can be loaded.
I did not yet implement it for full TV show / season loading, as we would likely hit TvMaze's rate limiting.
Before we can do that, we need to implement a custom rate limiter.
For #1801
> feat(TvMaze): Allow loading actor images for single-episode scrape jobs

- CHANGELOG.md
- src/scrapers/tv_show/SeasonScrapeJob.h
- src/scrapers/tv_show/custom/CustomSeasonScrapeJob.cpp
- src/scrapers/tv_show/tmdb/TmdbTvSeasonScrapeJob.cpp
If there is an unknown season, and you want to load _all_ episodes, MediaElch aborted scraping after failing to load the unknown season.
Fix #1692
> fix(TMDB): Don't abort after failing to load unknown season

- debian/control
It seems that ${shlibs:Depends} missed the dependency on libqt6svg6. Put it in the Depends to fix issues with svg images.
This should fix: https://github.com/Komet/MediaElch/issues/1859
> fix(debian: Add libqt6svg6 to the package dependencies

- src/ui/small_widgets/MusicTreeView.cpp
- src/ui/small_widgets/TvShowTreeView.cpp
Implicit conversions were disabled for the QChar() constructor in Qt 6.9.
Cast to supported argument type to keep backwards compatibility. Build tested with Qt 5.15.16 and Qt 6.9.0.
> Fix build with Qt 6.9

- CHANGELOG.md
- src/network/DownloadManager.cpp
- src/ui/tv_show/TvShowWidgetEpisode.cpp
- src/ui/tv_show/TvShowWidgetEpisode.h
We did not reset the navigation bar, i.e. all navigation icons remained greyed out.
Fix #1896
> fix(TvShow): Properly reset navigation bar after downloads are finished
