- movies/MovieSearchWidget.cpp
- renamer/Renamer.cpp
Allow to create directory if the source is not set in separate folder and rename folder is checked.
After move all movie files in the folder.
> Change Movies renamer

- scrapers/AEBN.cpp
- scrapers/AdultDvdEmpire.cpp
- scrapers/HotMovies.cpp
AEBN, Hotmovies and AdultDvdEmpire fixed and working again
> Adult Scraper fixed

- globals/ImageDialog.cpp
- imageProviders/FanartTv.cpp
- imageProviders/FanartTvMusic.cpp
- imageProviders/FanartTvMusicArtists.cpp
- imageProviders/TheTvDbImages.cpp
- movies/MovieWidget.cpp
- scrapers/CustomMovieScraper.cpp
- scrapers/IMDB.cpp
- scrapers/TMDb.cpp
- scrapers/TMDbConcerts.cpp
- scrapers/TheTvDb.cpp
- scrapers/TvTunes.cpp
- scrapers/UniversalMusicScraper.cpp
- trailerProviders/HdTrailers.cpp
- tvShows/TvShowUpdater.cpp
- use all HTTPS with all scrapers that are reachable over HTTPS
> use https with scrapers that support it

- .gitignore
- scripts/create_fakes.sh
- scripts/fake_data/movies_en.txt
- scripts/fake_data/tvshows_en/Game_Of_Thrones/Season_01.txt
- scripts/fake_data/tvshows_en/Game_Of_Thrones/Season_02.txt
- scripts/fake_data/tvshows_en/Game_Of_Thrones/Season_04.txt
- add fake data (top ~100 movies of all time; GoT episodes)
- the data has multiple formats: spaces, hyphens and underscores
I might add other tv shows, music albums, etc.
The script generates all required directories so that MediaElch can find them. A test `mov` file is created. The file itself is not valid but this might change in the future.
> Add script to generate fake data

- data/TvShow.cpp
- mediaCenterPlugins/XbmcXml.cpp
fix export of show status to `.nfo` file
> Fix show status export

- .gitignore
- scripts/create_fakes.sh
- scripts/fake_data/music/Rammstein/Liebe ist für alle da.txt
- scripts/fake_data/music/Rammstein/Reise Reise.txt
- scripts/fake_data/music/Rammstein/Rosenrot.txt
- scripts/fake_data/music/Rammstein/Sehnsucht.txt
- add an artist and some albums
> Add fake music

- scrapers/IMDB.cpp
- scrapers/IMDB.h
- IMDB has switched to loading images with JavaScript instead
of `<img>` elements
> Fix IMDB poster scraper

- export/ExportDialog.cpp
Stumbled upon this while working on the other PR :)
> Fix export of STUDIO.NAME (was using country)

- MediaElch.pro
- concerts/ConcertWidget.cpp
- downloads/ImportDialog.cpp
- export/ExportTemplate.cpp
- globals/Helper.cpp
- globals/ImageDialog.cpp
- globals/TrailerDialog.cpp
- image/ImageModel.cpp
- imageProviders/FanartTv.cpp
- imageProviders/FanartTvMusic.cpp
- imageProviders/FanartTvMusicArtists.cpp
- movies/MovieWidget.cpp
- scrapers/CustomMovieScraper.cpp
- scrapers/TMDb.cpp
- scrapers/TMDbConcerts.cpp
- sets/SetsWidget.cpp
- smallWidgets/ClosableImage.cpp
- smallWidgets/FilterWidget.cpp
- smallWidgets/MyTableWidgetItem.cpp
- tvShows/TvShowWidgetEpisode.cpp
- tvShows/TvShowWidgetSeason.cpp
- tvShows/TvTunesDialog.cpp
> Enable gcc warnings; fix warnings

- scripts/create_fakes.sh
- scripts/fake_data/tvshows_en/Scrubs/Season_01.txt
- scripts/fake_data/tvshows_en/Scrubs/Season_04.txt
- scripts/fake_data/tvshows_en/Scrubs/Season_05.txt
- scripts/fake_data/tvshows_en/Scrubs/Season_07.txt
- add another tvshow with 4 seasons
- fix `create_fakes.sh` script
> Add further tvshow example data

- MediaElch.pro
- Version.h
- main.cpp
- main/AboutDialog.cpp
- main/AboutDialog.h
- main/AboutDialog.ui
Add developer information to the about dialog. This makes it easier if users experience problems. :smile: 
Some screenshots.
> [About] Add developer information

- main.cpp
> [Stylesheet] Fix css loading

- README.md
- doc/AdvancedSettings.md
- doc/ExportTheme.md
- doc/FAQ.md
- doc/KodiSynchronization.md
- doc/MusicScraping.md
- doc/PortableMode.md
- doc/RenamingFiles.md
I added some documentation for users (most is copied from the MediaElch forum).
> Add user documentation

- changelog.md
- scrapers/IMDB.cpp
> [IMDB] Fix plot scraping

- travis-ci/package.sh
> [Travis] AppImage workaround for Ubuntu 14.04

- Build.md
- MediaElch.pro
- Version.h
- debian/control
- main/MainWindow.cpp
- scrapers/CustomMovieScraper.cpp
- scrapers/TMDbConcerts.cpp
- scrapers/TMDbConcerts.h
- travis-ci/install_dependencies.sh
- travis-ci/win/dll_list.txt
- Remove last occurrence of QScript
> [TMDb Concert] Remove QScript

- data/MovieFileSearcher.cpp
Added -behindthescenes, -deleted, -featurette, -interview, -scene, -short to be ignored when scanning for media files.
> Added other extras to be ignored

- changelog.md
- scrapers/IMDB.cpp
- scrapers/IMDB.h
> [IMDb] Load all tags

- smallWidgets/MusicTreeView.cpp
- smallWidgets/MusicTreeView.h
- smallWidgets/TvShowTreeView.cpp
> Fix treeview for TV shows and music artists

- smallWidgets/TvShowTreeView.cpp
- smallWidgets/TvShowTreeView.h
This PR depends on #477  
I'll rebase this PR as soon as #477 is merged.
-------------
This PR fixes #478
>  [TvShow] Fix icon glitch 

- globals/TrailerDialog.cpp
- globals/TrailerDialog.h
This PR depends on #477  
I'll rebase this PR as soon as #477 is merged.
---------------
This PR fixes #480 by showing better error messages to the user (404/ can't play/ etc.).
>  [Trailer] Show better error messages 

- renamer/RenamerPlaceholders.ui
- ui/default.css
> [Renamer] Fix group box title ui

- downloads/ImportDialog.cpp
- downloads/ImportDialog.h
- downloads/MakeMkvDialog.cpp
- main/MainWindow.cpp
- main/MainWindow.h
- renamer/Renamer.cpp
- renamer/Renamer.h
- renamer/RenamerPlaceholders.cpp
- renamer/RenamerPlaceholders.h
- settings/Settings.cpp
- settings/Settings.h
- RenameType, RenameResult and RenameOperation: Use scoped enum
> [Renamer] Use scoped enums

- changelog.md
- scrapers/AdultDvdEmpire.cpp
> [ADE] Fix backdrop scraping

- data/MovieModel.cpp
- movies/FilesWidget.cpp
- movies/Movie.cpp
- movies/Movie.h
> [IMDb] Show green icon only if movie has valid IMDb id

- concerts/ConcertWidget.cpp
- downloads/ImportDialog.cpp
- downloads/MakeMkvDialog.cpp
- globals/ImageDialog.cpp
- main/Message.cpp
- movies/MovieWidget.cpp
- scrapers/TheTvDb.cpp
- sets/SetsWidget.cpp
- smallWidgets/ClosableImage.cpp
- smallWidgets/FilterWidget.cpp
- smallWidgets/ImageGallery.cpp
- smallWidgets/MyLineEdit.cpp
- tvShows/TvShowWidgetEpisode.cpp
- tvShows/TvShowWidgetSeason.cpp
- tvShows/TvShowWidgetTvShow.cpp
Using AddressSanitizer, I found some leaks. The current implementation of FilterWidget still has some memory leaks but we need some other structure for that.
> Fix some memory leaks

- Version.h
- main.cpp
> Fix macOS preferences location

- smallWidgets/TvShowTreeView.cpp
Fix #545 
This temporary solution is taken from the previous version.
> [Windows] TvShows selection background

- renamer/Renamer.cpp
> [Renamer] Fix showTitle placeholder in season directory

- scrapers/IMDB.cpp
> [Scraper] Fix IMDb scraping

- changelog.md
- scrapers/AdultDvdEmpire.cpp
> [Scraper] Fix ADE search

- scrapers/KinoDe.cpp
- scrapers/TMDb.cpp
- scrapers/TMDb.h
- test/helpers/debug_output.h
- test/scrapers/testIMDb.cpp
- test/scrapers/testKinoDe.cpp
- test/scrapers/testTMDb.cpp
Part 3 of writing tests. This time I actually found one minor problem with TMDb and a few broken details with KinoDe :tada:
> [Test] Add more scraper tests

- MediaElch.pro
- data/Movie.cpp
- data/Movie.h
- data/Rating.cpp
- data/Rating.h
- data/TvShow.cpp
- data/TvShow.h
- data/TvShowEpisode.cpp
- data/TvShowEpisode.h
Part 2 of many: Current data models are huge. I'll try to split them into smaller ones.
> [Rating] Add rating class

- changelog.md
- scrapers/VideoBuster.cpp
- test/scrapers/testIMDb.cpp
- test/scrapers/testVideoBuster.cpp
Fixes an edge case with VideoBuster where "FSK 0" is not recognized.
> [Test] Add VideoBuster scraping test

- changelog.md
- src/main/MainWindow.cpp
> [Renamer] Enable concert renaming

- MediaElch.pro
- src/scrapers/TMDb.cpp
- test/scrapers/testTMDb.cpp
> [TMDb] Remove leading "id" from TMDb ID

- changelog.md
- src/downloads/MakeMkvCon.cpp
- src/main/MainWindow.cpp
- src/mediaCenterPlugins/XbmcXml.cpp
- src/movies/MovieDuplicateItem.cpp
- src/movies/MovieDuplicateItem.h
- src/movies/MovieDuplicates.cpp
- src/movies/MovieDuplicates.h
- src/movies/MovieDuplicates.ui
- src/scrapers/AEBN.cpp
- src/scrapers/AEBN.h
- src/scrapers/HotMovies.cpp
- src/scrapers/IMDB.cpp
- src/scrapers/KinoDe.cpp
- src/scrapers/OFDb.cpp
- src/scrapers/TheTvDb.cpp
- src/scrapers/UniversalMusicScraper.cpp
- src/scrapers/VideoBuster.cpp
- test/scrapers/testIMDb.cpp
- test/scrapers/testTMDb.cpp
- Fixes #587 
- Fixes #556
- Fixes #590 
- Fixes #591
> [Develop] Merge develop branch

- src/concerts/ConcertSearchWidget.cpp
- src/movies/MovieMultiScrapeDialog.cpp
- src/movies/MovieSearchWidget.cpp
- src/music/MusicMultiScrapeDialog.cpp
- src/music/MusicSearchWidget.cpp
- src/tvShows/TvShowMultiScrapeDialog.cpp
- src/tvShows/TvShowSearch.cpp
> [Search] Use trimmed titles for searching

- src/image/ImageWidget.ui
> [ImageWidget] Fix QQuickWidget header class name

- CHANGELOG.md
- MediaElch.plist
- Version.h
- debian/changelog
- obs/MediaElch.changes
- obs/MediaElch.spec
- obs/README.md
- src/globals/TrailerDialog.cpp
- src/main/AboutDialog.cpp
- src/main/AboutDialog.ui
- src/main/MyIconFont.cpp
- src/main/MyIconFont.h
- src/scrapers/IMDB.cpp
- src/scrapers/TMDbConcerts.cpp
- src/scrapers/UniversalMusicScraper.cpp
- src/support/SupportDialog.ui
This PR prepares MediaElch for the next release. PR #599 should be merged first. :-)
I noticed that previous version names are based on StarTrek planets and races so I propose the name 'Ferenginar' (I've never watched StarTrek before so I'm open to alternatives :smiley:  )  
http://memory-alpha.wikia.com/wiki/Category:Planets
Below is some text that I'd like to publish on forum.kodi.tv
----------------
The next version 2.6.0 named "Ferenginar" is finally ready to download.
This version fixes more than 20 bugs, has multiple small improvements and adds various features.
MediaElch now uses "https" for all scrapers that support it. Few new audio and video codecs are now recognized as well. We now support renaming concerts, creating subdirectories and detecting duplicate movies, updated fixed …
> [Release] Prepare next version

- MediaElch.plist
Disabling the dark mode in Mojave.
> [macOS] Dark mode disable

- CHANGELOG.md
- src/data/TvShowModel.cpp
- src/movies/MovieFilesWidget.cpp
- src/movies/MovieFilesWidget.h
- src/movies/MovieFilesWidget.ui
- src/ui/default.css
- src/ui/small_widgets/TvShowTreeView.cpp
> [UI] Fix regressions

- scripts/packaging/package.sh
- travis-ci/package.sh
- AppImage packaging is broken
- Windows build now uses latest ffmpeg version
> [Packaging] Update ffmpeg

- CHANGELOG.md
- src/movies/MovieSearchWidget.ui
- src/music/MusicSearchWidget.ui
- src/tvShows/TvShowSearch.ui
> [Search] Restructure checkboxes; reduce height

- CHANGELOG.md
- src/globals/Filter.cpp
> [Filter] Fix inversed "has no IMDb id" filter

- CHANGELOG.md
- src/main.cpp
> [Main] Load settings before first usage

- src/ui/default.css
> [ui] Scrapers ComboBox style fix

- CHANGELOG.md
- travis-ci/package.sh
> [Packaging] Add qtwindowsvistastyle.dll for Windows

- CHANGELOG.md
- src/scrapers/AdultDvdEmpire.cpp
- test/scrapers/testAdultDvdEmpire.cpp
- test/scrapers/testHotMovies.cpp
> [Scraper] Fix ADE scraper; add test cases

- CHANGELOG.md
- src/scrapers/movie/AdultDvdEmpire.cpp
- test/scrapers/testAdultDvdEmpire.cpp
> [Scraper] Fix actor scraping of ADE

- travis-ci/win/dll_list.txt
> [Packaging][Windows] Add missing libwinpthread-1.dll

- CMakeLists.txt
- scripts/packaging/package.sh
- src/file/CMakeLists.txt
- src/ui/music/CMakeLists.txt
- src/ui/settings/SettingsWindow.cpp
- src/ui/settings/SettingsWindow.h
- travis-ci/package.sh
- also fixes a bug introduced in a previous PR
> [Scripts] Fix package scripts

- CHANGELOG.md
- MediaElch.pro
- src/concerts/ConcertFileSearcher.cpp
- src/concerts/ConcertFileSearcher.h
- src/movies/MovieFileSearcher.cpp
- src/movies/MovieFileSearcher.h
- src/music/MusicFileSearcher.cpp
- src/music/MusicFileSearcher.h
- src/tv_shows/TvShowFileSearcher.cpp
- src/tv_shows/TvShowFileSearcher.h
- src/ui/downloads/DownloadsWidget.cpp
- src/ui/main/FileScannerDialog.cpp
- src/ui/main/FileScannerDialog.h
- src/ui/main/MainWindow.cpp
- src/ui/main/MainWindow.h
> [FileSearcher] Fix TV shows always beeing reloaded

- CMakeLists.txt
- cmake/coverage.cmake
- scripts/run_cmake_format.sh
- src/CMakeLists.txt
- src/export/CMakeLists.txt
- src/export/ExportTemplateLoader.cpp
- src/tv_shows/CMakeLists.txt
- src/tv_shows/TvShowUpdater.cpp
- third_party/CMakeLists.txt
- related #758
- fix some clang-format issues
- fix some cmake-format issues
> [CMake] Use modern CMake for external QuaZip usage

- CMakeLists.txt
Issue #756 was incomplete. Description was copy/pasted from above line
but not updated to reflect intent. Edited text.
> Correct description text in CMake file

- src/main.cpp
- src/ui/concerts/ConcertFilesWidget.cpp
- src/ui/concerts/ConcertWidget.cpp
- src/ui/downloads/DownloadsWidget.cpp
- src/ui/main/FileScannerDialog.cpp
- src/ui/main/MainWindow.cpp
- src/ui/main/MainWindow.ui
- src/ui/main/MyIconFont.cpp
- src/ui/movies/MovieFilesWidget.cpp
- src/ui/movies/MovieMultiScrapeDialog.cpp
- src/ui/music/MusicMultiScrapeDialog.cpp
- src/ui/small_widgets/ClosableImage.cpp
- src/ui/small_widgets/ImageLabel.cpp
- src/ui/small_widgets/LoadingStreamDetails.cpp
- src/ui/tv_show/TvShowFilesWidget.cpp
- src/ui/tv_show/TvShowMultiScrapeDialog.cpp
- src/ui/tv_show/TvShowWidgetEpisode.cpp
- src/ui/tv_show/TvShowWidgetSeason.cpp
- src/ui/tv_show/TvShowWidgetTvShow.cpp
- fix #645
- circle was too small for three-digit-numbers
> [UI] Increase bubble size on macOS

- CMakeLists.txt
- src/globals/DownloadManager.cpp
- src/globals/DownloadManager.h
- src/globals/Manager.cpp
- src/tv_shows/TvShow.cpp
- src/tv_shows/TvShow.h
- src/ui/tv_show/TvShowWidgetTvShow.cpp
- may fix #716
- fixes crashes on selecting an actor in the TV show panel
> [TvShow] Fix crash on selecting actors

- MediaElch.pro
- scripts/build_release.sh
- travis-ci/docker/Dockerfile.build-opensuse-leap-15
- travis-ci/docker/Dockerfile.build-opensuse-leap-42.3
- travis-ci/docker/Dockerfile.build-opensuse-tumbleweed
- travis-ci/docker/Dockerfile.build-ubuntu-16.04
- travis-ci/docker/Dockerfile.build-ubuntu-18.04
- travis-ci/docker/Dockerfile.build-ubuntu-19.04
- travis-ci/docker/README.md
- travis-ci/docker/build-opensuse.sh
- travis-ci/docker/build-ubuntu.sh
- travis-ci/docker/docker-build-all.sh
- travis-ci/docker/docker-build-dist.sh
For testing locally with different operating systems.
> [CI] Add Docker files

- .travis.yml
- README.md
- cmake/coverage.cmake
We use Codecov for coverage reporting. Works quite well :)
> [TravisCI] Enable coverage reporting

- src/media_centers/kodi/v16/ConcertXmlWriterV16.h
- src/media_centers/kodi/v17/ConcertXmlWriterV17.h
- src/ui/main/MainWindow.cpp
>  [MainWindow] Renew TV show model after file searcher is finished

- CHANGELOG.md
- MediaElch.pro
- docs/advancedsettings.xml
- src/image/CMakeLists.txt
- src/image/ImageCapture.cpp
- src/image/ImageCapture.h
- src/image/ThumbnailDimensions.cpp
- src/image/ThumbnailDimensions.h
- src/media_centers/KodiXml.cpp
- src/settings/AdvancedSettings.cpp
- src/settings/AdvancedSettings.h
- src/settings/Settings.cpp
- src/ui/tv_show/TvShowWidgetEpisode.cpp
- test/unit/CMakeLists.txt
- test/unit/settings/testAdvancedSettings.cpp
- new `advancedsettings.xml` tag:
- `<episodeThumb>` with `<width>` and `<height>`
- default is 400x300
- will keep aspect ratio
- fixes #776
> [Image] Make thumbnail size configurable

- src/globals/DownloadManager.cpp
- src/globals/DownloadManager.h
> [DownloadManager] Fix deadlock

- CHANGELOG.md
- docs/advancedsettings.xml
- src/data/StreamDetails.cpp
- src/settings/AdvancedSettings.cpp
- src/ui/main/AboutDialog.cpp
> [StreamDetails] Add "avc" to "h264" default codec mapping

- CHANGELOG.md
- src/media_centers/kodi/MovieXmlReader.cpp
- src/media_centers/kodi/v17/MovieXmlWriterV17.cpp
- src/movies/MovieSet.h
- src/scrapers/movie/TMDb.cpp
- src/scrapers/movie/TMDb.h
- src/ui/movies/MovieSearchWidget.cpp
- test/integration/media_centers/testKodi_v16_movie.cpp
- test/integration/media_centers/testKodi_v18_movie.cpp
- test/resources/movie/kodi_v18_movie_all.nfo
- test/scrapers/testTMDb.cpp
- [Scraper] Fix default-selected language not being used  
faulty implementation added in v2.6.0
- [TMDb] Load movie collection details  
Ping @monisriz : We now load the collection's overview :smiley:  
It's already saved to the NFO file but isn't available in the UI, yet.
Related issue: #800
> [TMDb] Load movie collection details

- src/scrapers/concert/TMDbConcerts.cpp
- src/scrapers/movie/TMDb.cpp
Updating the base url for images.
Reference: https://developers.themoviedb.org/3/getting-started/images
Issue: https://github.com/Komet/MediaElch/issues/807
> base url update

- CHANGELOG.md
- docs/admin/README.md
- docs/admin/who-to-follow.md
- src/ui/main/AboutDialog.cpp
> [AboutDialog] Fix MediaInfo version on windows

- CHANGELOG.md
- src/scrapers/movie/AdultDvdEmpire.cpp
- test/scrapers/testAdultDvdEmpire.cpp
- fixes #819
- distinguish between DVDs, BlueRays and VOD in search
> [ADA] Don't filter for DVDs; distinguish between DVDs and VOD in search

- CHANGELOG.md
- src/media_centers/kodi/v17/TvShowXmlWriterV17.cpp
- test/resources/concert/kodi_v18_concert_empty.nfo
- test/resources/movie/kodi_v16_movie_all.nfo
- test/resources/movie/kodi_v16_movie_empty.nfo
- test/resources/movie/kodi_v18_Alien_1979.nfo
- test/resources/movie/kodi_v18_Toy_Story_3_2010.nfo
- test/resources/movie/kodi_v18_movie_all.nfo
- test/resources/movie/kodi_v18_movie_empty.nfo
- test/resources/show/kodi_v18_show_Game_of_Thrones.nfo
- test/resources/show/kodi_v18_show_Torchwood.nfo
> [TvShowXmlWriter] Don't write TheTvDb v1 episodeguide URLs to NFO files

- src/export/ExportTemplateLoader.cpp
- src/globals/VersionInfo.cpp
- src/media_centers/kodi/EpisodeXmlReader.cpp
- src/media_centers/kodi/TvShowXmlReader.cpp
- src/scrapers/movie/AdultDvdEmpire.cpp
- src/scrapers/movie/TMDb.cpp
- src/scrapers/tv_show/TheTvDb.cpp
- src/scrapers/tv_show/TheTvDb/EpisodeLoader.cpp
- src/scrapers/tv_show/TheTvDb/ShowLoader.cpp
- src/scrapers/tv_show/TheTvDb/ShowParser.cpp
- src/settings/AdvancedSettings.cpp
- src/settings/AdvancedSettings.h
- src/settings/AdvancedSettingsXmlReader.cpp
- src/tv_shows/EpisodeNumber.h
- src/tv_shows/SeasonNumber.h
- src/tv_shows/TvDbId.h
- src/tv_shows/TvShowUpdater.cpp
- src/ui/downloads/DownloadsWidget.cpp
- src/ui/main/MainWindow.cpp
- src/ui/notifications/Notificator.cpp
See https://forum.kodi.tv/showthread.php?tid=136333&pid=2913499#pid2913499
> [ShowParser] Save "tvdb" as rating source to NFO

- src/scrapers/tv_show/TheTvDb/EpisodeParser.cpp
- test/scrapers/TheTvDb/testShowLoader.cpp
Fix #848 
FYI: TheTvDb seems to be under heavy load at the moment.
> [TheTvDb] Fix loading of DVD order episodes

- src/media_centers/KodiXml.cpp
- src/media_centers/kodi/v16/MovieXmlWriterV16.cpp
- src/media_centers/kodi/v16/TvShowXmlWriterV16.cpp
- src/media_centers/kodi/v17/AlbumXmlWriterV17.cpp
- src/media_centers/kodi/v17/ConcertXmlWriterV17.cpp
- src/media_centers/kodi/v17/MovieXmlWriterV17.cpp
- src/media_centers/kodi/v17/TvShowXmlWriterV17.cpp
> [NfoWriters] Remove old v16 tags

- src/scrapers/movie/AEBN.cpp
- src/scrapers/movie/AdultDvdEmpire.cpp
- src/scrapers/movie/HotMovies.cpp
- src/scrapers/movie/IMDB.cpp
- src/scrapers/movie/OFDb.cpp
- src/scrapers/movie/TMDb.cpp
- src/scrapers/movie/VideoBuster.cpp
- test/scrapers/testIMDb.cpp
- test/scrapers/testTMDb.cpp
- test/scrapers/testVideoBuster.cpp
> [Scrapers] Clear actors before adding them two avoid duplicates

- CHANGELOG.md
- src/concerts/ConcertController.cpp
- src/globals/ImageDialog.cpp
- src/globals/ImageDialog.h
- src/movies/MovieController.cpp
- src/music/AlbumController.cpp
- src/music/ArtistController.cpp
- src/scrapers/ScraperInterface.h
- src/scrapers/image/FanartTv.cpp
- src/scrapers/image/FanartTvMusic.cpp
- src/scrapers/image/FanartTvMusicArtists.cpp
- src/scrapers/image/ImageProviderInterface.h
- src/scrapers/image/TMDbImages.cpp
- src/scrapers/image/TheTvDbImages.cpp
- src/ui/tv_show/TvShowMultiScrapeDialog.cpp
- src/ui/tv_show/TvShowWidgetTvShow.cpp
> [ImageProvider] Show error if provider fails retrieving images (e.g. network failure)

- CHANGELOG.md
- src/media_centers/kodi/v17/TvShowXmlWriterV17.cpp
- test/resources/show/kodi_v18_show_all.nfo
- test/resources/show/kodi_v18_show_empty.nfo
fix #652
Keep https://github.com/Komet/MediaElch/issues/888 in mind.
> [TvShowXmlWriter] Always write the episode guide URL using TVDb format

- src/export/SimpleEngine.cpp
> export images with different file-endings

- CHANGELOG.md
- src/globals/Helper.cpp
- src/globals/Helper.h
- src/ui/main/Update.cpp
- src/ui/main/Update.h
> [Updater] Use new MediaElch meta repository

- CHANGELOG.md
- src/scrapers/movie/HotMovies.cpp
Due to a change on their website, the vote count scraping did not work
anymore.
> [HotMovies] Fix vote count scraping

- CHANGELOG.md
- MediaElch.pro
- src/media_centers/MediaCenterInterface.h
- src/movies/MovieController.cpp
- src/movies/MovieController.h
- src/scrapers/CMakeLists.txt
- src/scrapers/movie/IMDB.cpp
- src/scrapers/movie/IMDB.h
- src/scrapers/movie/imdb/ImdbMovieScraper.cpp
- src/scrapers/movie/imdb/ImdbMovieScraper.h
- src/ui/movies/MovieWidget.cpp
- src/ui/movies/MovieWidget.h
- test/scrapers/testIMDb.cpp
> [IMDB] Load actor images in higher resolution

- CHANGELOG.md
- src/tv_shows/TvShowEpisode.cpp
- src/tv_shows/TvShowFileSearcher.cpp
> [TvShow] Sanitize default episode filename (remove file suffix, etc.)

- CHANGELOG.md
- src/data/Database.cpp
- src/globals/ImageDialog.cpp
- src/globals/ImagePreviewDialog.cpp
- src/globals/ImagePreviewDialog.h
- src/ui/image/ImageWidget.cpp
- src/ui/main/MainWindow.cpp
- src/ui/movie_sets/MovieListDialog.cpp
- src/ui/movie_sets/SetsWidget.cpp
- src/ui/small_widgets/ClosableImage.cpp
> [Dialogs] Fix centering of dialogs

- src/ui/media_centers/KodiSync.cpp
- src/ui/media_centers/KodiSync.h
- src/ui/small_widgets/ImageGallery.cpp
- src/ui/tv_show/TvShowFilesWidget.cpp
See https://scan.coverity.com/projects/komet-mediaelch
> [Project] Fix some coverity warnings

- .gitignore
- .travis.yml
- CHANGELOG.md
- src/data/MediaInfoFile.cpp
- src/ui/main/AboutDialog.cpp
- travis-ci/README.md
- travis-ci/docker/Dockerfile.build-windows
- travis-ci/docker/README.md
- travis-ci/install_dependencies.sh
- travis-ci/package.sh
- travis-ci/utils.sh
- travis-ci/win/build_windows.sh
- travis-ci/win/dll_list.txt
- travis-ci/win/package_windows.sh
- travis-ci/win/prepare_bintray_windows.sh
By using my custom docker image https://hub.docker.com/repository/docker/archer96/mediaelch-mxe-qt we can use Qt 5.14.2 for Windows.
Fix #832
> [CI] Use custom docker image for Windows mxe builds

- CHANGELOG.md
- src/export/SimpleEngine.cpp
> [Export] Add CONCERT.{FILENAME,DIR} to exporter

- src/export/SimpleEngine.cpp
- src/export/SimpleEngine.h
> [Export] Only replace image placeholders if they are actually used 

- CHANGELOG.md
- src/image/ImageCapture.cpp
- src/image/ImageCapture.h
- src/scrapers/tv_show/thetvdb/ShowLoader.cpp
- src/ui/movies/MovieWidget.cpp
> [Movie] Allow screenshot for movie backdrop

- src/settings/Settings.cpp
"%2" was used but only one argument was passed.
> [Settings] Fix Storing of selected scrape details

- CHANGELOG.md
- src/scrapers/movie/IMDB.cpp
- src/scrapers/movie/IMDB.h
Supersedes #990 and #989 
@fialky Thanks for your change! I've refactored your change a bit to avoid code duplication. Search results and scraping works for the stuff I tested.
> [IMDb] Include adult search results if "Show Adult Scrapers" is enabled

- CHANGELOG.md
- src/data/Locale.cpp
- src/data/Locale.h
- src/scrapers/ScraperInterface.h
- src/scrapers/movie/AEBN.cpp
- src/scrapers/movie/AEBN.h
- src/scrapers/movie/AdultDvdEmpire.cpp
- src/scrapers/movie/AdultDvdEmpire.h
- src/scrapers/movie/CustomMovieScraper.cpp
- src/scrapers/movie/CustomMovieScraper.h
- src/scrapers/movie/HotMovies.cpp
- src/scrapers/movie/HotMovies.h
- src/scrapers/movie/IMDB.cpp
- src/scrapers/movie/IMDB.h
- src/scrapers/movie/MovieScraperInterface.h
- src/scrapers/movie/OFDb.cpp
- src/scrapers/movie/OFDb.h
- src/scrapers/movie/TMDb.cpp
- src/scrapers/movie/TMDb.h
- src/scrapers/movie/VideoBuster.cpp
- src/scrapers/movie/VideoBuster.h
- src/ui/movies/MovieSearchWidget.cpp
- src/ui/movies/MovieSearchWidget.h
Unify Locales throughout MediaElch.
> [Scrapers] Use Locale class instead of ScraperLanguage

- CHANGELOG.md
- src/globals/Actor.cpp
- src/globals/Actor.h
- src/network/NetworkRequest.cpp
- src/network/NetworkRequest.h
- src/scrapers/movie/AdultDvdEmpire.cpp
- test/scrapers/testAdultDvdEmpire.cpp
- test/scrapers/testHotMovies.cpp
> [ADE] Fix actor scraping

- CHANGELOG.md
- src/globals/Filter.cpp
- src/globals/Globals.h
- src/ui/movies/MovieWidget.cpp
- src/ui/movies/MovieWidget.h
- src/ui/movies/MovieWidget.ui
- src/ui/small_widgets/FilterWidget.cpp
- src/ui/small_widgets/MyLineEdit.cpp
> [Movie] Add TMDb ID to UI + "Open on Imdb/Tmdb" buttons 

- CHANGELOG.md
- src/ui/small_widgets/FilterWidget.cpp
- src/ui/small_widgets/FilterWidget.h
- src/ui/small_widgets/MyLineEdit.cpp
- src/ui/small_widgets/MyLineEdit.h
> [Filters] Also clear filters when clicking on 'X'

- src/export/SimpleEngine.cpp
I think this would be a good addition for themes
> add TVSHOW.SEASONS_AMOUNT

- CHANGELOG.md
- src/tv_shows/TvShow.cpp
- src/tv_shows/TvShowEpisode.cpp
- src/tv_shows/TvShowEpisode.h
- src/tv_shows/TvShowFileSearcher.cpp
- src/ui/imports/ImportDialog.cpp
- src/ui/main/MainWindow.cpp
- src/ui/tv_show/TvShowWidgetEpisode.cpp
> [TvShowEpisode] Allow forcing of episode reloads

- CHANGELOG.md
- src/globals/Filter.cpp
- src/globals/Filter.h
- src/globals/Globals.h
- src/ui/small_widgets/FilterWidget.cpp
- src/ui/small_widgets/MyLineEdit.cpp
> [Filter] Add filter for movie's original title

- src/scrapers/tv_show/ShowMerger.cpp
- src/scrapers/tv_show/ShowMerger.h
- src/scrapers/tv_show/custom/CustomEpisodeScrapeJob.cpp
- src/scrapers/tv_show/custom/CustomSeasonScrapeJob.cpp
- src/scrapers/tv_show/custom/CustomShowScrapeJob.cpp
- src/scrapers/tv_show/custom/CustomTvScraper.cpp
- src/tv_shows/TvShow.cpp
TheTvDb was always chosen.
Fix #1067
> [CustomTvScraper] Fix selection of wrong scraper + user-after-free bug

- CHANGELOG.md
- src/globals/ScraperInfos.cpp
- src/globals/ScraperInfos.h
- src/media_centers/kodi/EpisodeXmlReader.cpp
- src/media_centers/kodi/v16/EpisodeXmlWriterV16.cpp
- src/media_centers/kodi/v17/EpisodeXmlWriterV17.cpp
- src/scrapers/tv_show/ShowMerger.cpp
- src/scrapers/tv_show/custom/CustomTvScraper.cpp
- src/tv_shows/TvShowEpisode.cpp
- src/tv_shows/TvShowEpisode.h
- src/ui/settings/CustomTvScraperSettingsWidget.cpp
- src/ui/small_widgets/TagCloud.cpp
- src/ui/small_widgets/TagCloud.h
- src/ui/small_widgets/TagCloud.ui
- src/ui/tv_show/TvShowMultiScrapeDialog.cpp
- src/ui/tv_show/TvShowMultiScrapeDialog.ui
- src/ui/tv_show/TvShowSearchWidget.cpp
- src/ui/tv_show/TvShowSearchWidget.ui
- src/ui/tv_show/TvShowWidgetEpisode.cpp
- src/ui/tv_show/TvShowWidgetEpisode.h
- src/ui/tv_show/TvShowWidgetEpisode.ui
- test/resources/show/kodi_v18_episode_American_Dad_S02E01.nfo
- test/resources/show/kodi_v18_episode_American_Dad_S02E03-S02E04.nfo
> [Episode] Add episode tags

- CHANGELOG.md
- src/ui/small_widgets/SlidingStackedWidget.cpp
- src/ui/small_widgets/SlidingStackedWidget.h
- src/ui/tv_show/TvShowWidgetEpisode.cpp
> [UI] Don't always mark an episode changed if stream details are loaded

- CHANGELOG.md
- src/network/NetworkReplyWatcher.h
- src/scrapers/ScraperInterface.cpp
- src/scrapers/movie/HotMovies.cpp
- src/scrapers/movie/VideoBuster.cpp
- src/scrapers/movie/VideoBuster.h
- src/scrapers/movie/imdb/ImdbMovieScraper.cpp
- src/scrapers/movie/imdb/ImdbMovieScraper.h
- src/scrapers/tv_show/imdb/ImdbTvSeasonScrapeJob.cpp
- test/scrapers/testAEBN.cpp
- test/scrapers/testHotMovies.cpp
- test/scrapers/testTMDb.cpp
This is a batch PR. A lot of fixes before the next release.
> [Project] Fix scrapers, tests and some warnings

- MediaElch.pro
- scripts/quick_checks.sh
- src/concerts/Concert.cpp
- src/globals/CMakeLists.txt
- src/globals/Containers.cpp
- src/globals/Containers.h
- src/globals/Globals.h
- src/globals/NameFormatter.cpp
- src/globals/Random.cpp
- src/globals/Random.h
- src/image/ImageCapture.cpp
- src/media_centers/kodi/AlbumXmlReader.cpp
- src/media_centers/kodi/ArtistXmlReader.cpp
- src/media_centers/kodi/ConcertXmlReader.cpp
- src/media_centers/kodi/MovieXmlReader.cpp
- src/media_centers/kodi/MovieXmlReader.h
- src/media_centers/kodi/TvShowXmlReader.cpp
- src/movies/Movie.cpp
- src/scrapers/tv_show/custom/CustomEpisodeScrapeJob.cpp
- src/scrapers/tv_show/custom/CustomSeasonScrapeJob.cpp
- src/scrapers/tv_show/custom/CustomShowScrapeJob.cpp
- src/settings/AdvancedSettingsXmlReader.cpp
- src/ui/music/MusicSearchWidget.cpp
- src/ui/settings/ConcertSettingsWidget.cpp
- src/ui/settings/MovieSettingsWidget.cpp
- src/ui/settings/MusicSettingsWidget.cpp
- src/ui/settings/SettingsWindow.cpp
- src/ui/settings/TvShowSettingsWidget.cpp
- src/ui/small_widgets/ImageLabel.cpp
There are many methods/classes/... that are deprecated since Qt 5.10/5.14/5.15. This PR fixes most of them.
> Fix Qt deprecation warnings

- src/scrapers/movie/IMDB.cpp
- src/scrapers/movie/imdb/ImdbMovieScraper.cpp
See #1086
In preparation for #1088
> [IMDb] Use QRegularExpression instead of QRegEx

- CHANGELOG.md
- src/main.cpp
- src/settings/AdvancedSettings.cpp
- src/settings/AdvancedSettings.h
This reverts commit 03b7af99c2009fb116d280fd91c46e27e0ab8b7c.
Re-opens #1002
> Revert "[i18n] Use proper translation loading"

- CHANGELOG.md
- scripts/create_fakes.sh
- src/movies/file_searcher/MovieFileSearcher.cpp
> [MovieFileSearcher] Correctly kip BluRay BACKUP and STREAM folders

- src/data/Certification.cpp
- src/data/ImdbId.cpp
- src/data/MediaInfoFile.cpp
- src/data/StreamDetails.cpp
- src/imports/Extractor.cpp
- src/movies/MovieController.cpp
- src/renamer/Renamer.cpp
- src/scrapers/movie/OFDb.cpp
- src/scrapers/tv_show/thetvdb/TheTvDbApi.cpp
- src/settings/DataFile.cpp
- src/tv_shows/EpisodeNumber.cpp
- src/tv_shows/SeasonNumber.cpp
- src/ui/imports/ImportDialog.cpp
- src/ui/main/Update.cpp
> [Project] Replace QRegExp with QRegularExpression

- CHANGELOG.md
- MediaElch.pro
- src/media_centers/kodi/MovieXmlReader.cpp
- src/media_centers/kodi/TvShowXmlReader.cpp
- src/media_centers/kodi/v17/TvShowXmlWriterV17.cpp
- src/movies/Movie.cpp
- src/movies/Movie.h
- src/movies/MovieController.cpp
- src/scrapers/movie/CustomMovieScraper.cpp
- src/scrapers/movie/TMDb.cpp
- src/scrapers/movie/imdb/ImdbMovieScraper.cpp
- src/tv_shows/CMakeLists.txt
- src/tv_shows/TvMazeId.cpp
- src/tv_shows/TvMazeId.h
- src/tv_shows/TvShow.cpp
- src/tv_shows/TvShow.h
- src/ui/movies/MovieWidget.cpp
- src/ui/tv_show/TvShowWidgetTvShow.cpp
- src/ui/tv_show/TvShowWidgetTvShow.h
- src/ui/tv_show/TvShowWidgetTvShow.ui
- test/integration/media_centers/testKodi_v16_movie.cpp
- test/integration/media_centers/testKodi_v18_movie.cpp
- test/integration/media_centers/testKodi_v18_show.cpp
- test/resources/show/kodi_v18_show_Game_of_Thrones.nfo
- test/resources/show/kodi_v18_show_Torchwood.nfo
- test/resources/show/kodi_v18_show_all.nfo
- test/unit/CMakeLists.txt
- test/unit/tv_shows/testTvMazeId.cpp
> [TvShow] Add TVmaze ID to show

- src/media_centers/kodi/EpisodeXmlReader.cpp
- src/media_centers/kodi/v17/EpisodeXmlWriterV17.cpp
- src/tv_shows/TvShowEpisode.cpp
- src/tv_shows/TvShowEpisode.h
- src/ui/tv_show/TvShowWidgetEpisode.cpp
- src/ui/tv_show/TvShowWidgetEpisode.h
- src/ui/tv_show/TvShowWidgetEpisode.ui
- src/ui/tv_show/TvShowWidgetTvShow.ui
- test/integration/media_centers/testKodi_v18_episode.cpp
- test/resources/show/kodi_v18_episode_American_Dad_S02E01.nfo
- test/resources/show/kodi_v18_episode_American_Dad_S02E03-S02E04.nfo
> [TvShowEpisode] Add TVmaze ID to episode

- src/globals/Globals.h
> [Globals] Fix QString split behavior in Qt < 5.14

- src/cli/common.cpp
- src/globals/ScraperInfos.cpp
- src/movies/MovieFilesOrganizer.cpp
- src/scrapers/tv_show/imdb/ImdbTvEpisodeScrapeJob.cpp
- src/scrapers/tv_show/imdb/ImdbTvSeasonScrapeJob.cpp
- src/scrapers/tv_show/imdb/ImdbTvShowSearchJob.cpp
- src/scrapers/tv_show/thetvdb/TheTvDbSeasonScrapeJob.cpp
- src/scrapers/tv_show/thetvdb/TheTvDbSeasonScrapeJob.h
- src/tv_shows/SeasonOrder.cpp
- src/ui/small_widgets/AlphabeticalList.cpp
- src/ui/small_widgets/MediaFlags.cpp
- src/ui/tv_show/TvShowFilesWidget.cpp
- test/scrapers/imdbtv/testImdbTvEpisodeLoader.cpp
- test/scrapers/tmdbtv/testTmdbTvEpisodeLoader.cpp
This may result in crashes otherwise...
> [TvShowFilesWidget] Fix nullptr dereference 

- src/movies/MovieController.cpp
- src/scrapers/concert/TMDbConcerts.cpp
- src/scrapers/concert/TMDbConcerts.h
- src/scrapers/movie/AEBN.cpp
- src/scrapers/movie/AEBN.h
- src/scrapers/movie/AdultDvdEmpire.cpp
- src/scrapers/movie/AdultDvdEmpire.h
- src/scrapers/movie/CustomMovieScraper.cpp
- src/scrapers/movie/CustomMovieScraper.h
- src/scrapers/movie/HotMovies.cpp
- src/scrapers/movie/HotMovies.h
- src/scrapers/movie/IMDB.cpp
- src/scrapers/movie/IMDB.h
- src/scrapers/movie/OFDb.cpp
- src/scrapers/movie/OFDb.h
- src/scrapers/movie/TMDb.cpp
- src/scrapers/movie/TMDb.h
- src/scrapers/movie/VideoBuster.cpp
- src/scrapers/movie/VideoBuster.h
- src/scrapers/music/UniversalMusicScraper.cpp
- src/scrapers/music/UniversalMusicScraper.h
- src/ui/imports/ImportDialog.cpp
- src/ui/imports/MakeMkvDialog.cpp
- src/ui/movies/MovieMultiScrapeDialog.cpp
- src/ui/movies/MovieSearchWidget.cpp
- src/ui/movies/MovieWidget.cpp
- src/ui/settings/ScraperSettingsWidget.cpp
Be consistent with the new TV scraper.
> [MovieScraper] Rename static "scraperIdentifier" to "ID"

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/scraper-does-not-work.md
- CHANGELOG.md
- CMakeLists.txt
- MediaElch.plist
- Version.h
- debian/changelog
- docs/admin/release.md
- obs/MediaElch.spec
- obs/README.md
There are two regressions that I really want to fix. I also found a nullptr dereference which may lead to crashes in the future.
> [Release] Prepare release of v2.8.2

- src/movies/file_searcher/MovieFileSearcher.cpp
> [MovieFilter] Fix folder exclusion

- CHANGELOG.md
- docs/advancedsettings.xml
- src/settings/AdvancedSettings.cpp
> [AdvancedSettings] Add "*.webm" to default video filters

- CHANGELOG.md
- src/globals/ImageDialog.cpp
- src/globals/ImageDialog.h
- src/scrapers/movie/TMDb.cpp
- src/scrapers/tv_show/thetvdb/TheTvDbShowSearchJob.cpp
- src/scrapers/tv_show/tmdb/TmdbTvShowSearchJob.cpp
- src/ui/concerts/ConcertWidget.cpp
- src/ui/movie_sets/SetsWidget.cpp
- src/ui/movies/MovieWidget.cpp
- src/ui/music/MusicWidgetAlbum.cpp
- src/ui/music/MusicWidgetArtist.cpp
- src/ui/tv_show/TvShowWidgetEpisode.cpp
- src/ui/tv_show/TvShowWidgetSeason.cpp
- src/ui/tv_show/TvShowWidgetTvShow.cpp
This was a really annoying bug. Multiple smaller issues were combined but this PR fixes it. :-)
> [ImageDialog] Fix immediate "network error"-message

- .ci/docker/Dockerfile.build-windows
- CHANGELOG.md
- src/globals/DownloadManager.cpp
- src/globals/DownloadManager.h
- src/ui/main/MainWindow.cpp
- src/ui/movie_sets/SetsWidget.cpp
> [SetsWidget] Fix adding movie to set

- CHANGELOG.md
- src/renamer/MovieRenamer.cpp
- src/renamer/Renamer.cpp
- src/renamer/Renamer.h
- src/renamer/RenamerDialog.ui
- src/renamer/RenamerPlaceholders.ui
> [MovieRenamer] Support `<studio>` which contains the movie's studio(s) 

- CHANGELOG.md
- MediaElch.pro
- src/export/CMakeLists.txt
- src/export/CsvExport.cpp
- src/export/CsvExport.h
- src/globals/Helper.cpp
- src/ui/export/CMakeLists.txt
- src/ui/export/CsvExportDialog.cpp
- src/ui/export/CsvExportDialog.h
- src/ui/export/CsvExportDialog.ui
- src/ui/main/MainWindow.cpp
- src/ui/main/MainWindow.h
- src/ui/main/Navbar.cpp
Add simple CSV export functionality. It comes with a (for now) hidden
dialog box that can be opened using Ctrl+Shift+E.
Only movies are supported as of now. More may come.
See #1139
> [Export] Add CSV export functionality for movies

- CHANGELOG.md
- MediaElch.pro
- src/cli/main.cpp
- src/scrapers/CMakeLists.txt
- src/scrapers/music/AllMusic.cpp
- src/scrapers/music/AllMusic.h
- src/scrapers/music/Discogs.cpp
- src/scrapers/music/Discogs.h
- src/scrapers/music/MusicBrainz.cpp
- src/scrapers/music/MusicBrainz.h
- src/scrapers/music/TheAudioDb.cpp
- src/scrapers/music/TheAudioDb.h
- src/scrapers/music/UniversalMusicScraper.cpp
- src/scrapers/music/UniversalMusicScraper.h
> [AllMusic] Strip HTML elements from "formed" field

- CHANGELOG.md
- MediaElch.pro
- src/music/CMakeLists.txt
- src/music/TheAudioDbId.cpp
- src/music/TheAudioDbId.h
- src/scrapers/music/MusicBrainz.cpp
- src/scrapers/music/MusicBrainz.h
- src/scrapers/music/TheAudioDb.cpp
- src/scrapers/music/TheAudioDb.h
- src/scrapers/music/UniversalMusicScraper.cpp
> [UniversalMusicScraper] Add MusicBrainz as artist's biography source

- .gitignore
- src/data/MediaInfoFile.cpp
- src/export/SimpleEngine.cpp
- src/globals/Helper.cpp
- src/imports/DownloadFileSearcher.cpp
- src/imports/MakeMkvCon.cpp
- src/media_centers/KodiXml.cpp
- src/scrapers/trailer/HdTrailers.cpp
- src/tv_shows/EpisodeNumber.cpp
- src/ui/export/CsvExportDialog.cpp
Only replace the easy ones. Other come step by step.
See #1086
> [Project] Replace QRegEx with QRegularExpression at most places

- src/export/CsvExport.cpp
- src/export/CsvExport.h
- src/ui/export/CsvExportDialog.cpp
- src/ui/export/CsvExportDialog.h
- src/ui/export/CsvExportDialog.ui
- src/ui/small_widgets/MessageLabel.cpp
- src/ui/small_widgets/MessageLabel.h
> [CsvExport] Improve export dialog, add more export types

- CHANGELOG.md
- src/network/NetworkRequest.cpp
- src/scrapers/ScraperInterface.cpp
- src/scrapers/ScraperInterface.h
- src/scrapers/movie/adultdvdempire/AdultDvdEmpire.cpp
- src/scrapers/movie/adultdvdempire/AdultDvdEmpireApi.cpp
- src/scrapers/movie/aebn/AEBN.cpp
- src/scrapers/movie/hotmovies/HotMovies.cpp
- src/scrapers/movie/imdb/ImdbMovieScraper.cpp
- src/scrapers/movie/videobuster/VideoBuster.cpp
- test/scrapers/imdbtv/testImdbTvShowSearch.cpp
- test/scrapers/tmdbconcert/testTmdbConcert.cpp
Fix #1164
See https://github.com/Komet/MediaElch/issues/1164#issuecomment-756637833
> [ADE] Fix actor image scraping 

- src/scrapers/movie/adultdvdempire/AdultDvdEmpire.cpp
- src/scrapers/movie/adultdvdempire/AdultDvdEmpire.h
- src/scrapers/tv_show/imdb/ImdbTvShowParser.cpp
- src/scrapers/tv_show/tvmaze/TvMazeShowScrapeJob.cpp
> [ADE] Fix empty actor issue

- src/export/CsvExport.cpp
- src/export/CsvExport.h
- src/settings/Settings.cpp
- src/settings/Settings.h
- src/ui/export/CsvExportDialog.cpp
- src/ui/export/CsvExportDialog.h
- src/ui/main/MainWindow.cpp
> [CsvExport] Save field checkstate in settings

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/scraper-does-not-work.md
- CHANGELOG.md
- CMakeLists.txt
- MediaElch.plist
- Version.h
- docs/admin/release.md
- obs/MediaElch.spec
- obs/README.md
> [Release] Prepare release of v2.8.4

- data/desktop/MediaElch.desktop
`Database` because you can update the Kodi-Database
> .desktop-file add categories

- CHANGELOG.md
- src/export/CsvExport.cpp
- src/export/CsvExport.h
- src/ui/export/CsvExportDialog.cpp
> [CSV Export] Add directory and filenames to export options

- CHANGELOG.md
- src/export/CsvExport.cpp
- src/export/CsvExport.h
- src/export/SimpleEngine.cpp
- src/media_centers/kodi/TvShowXmlReader.cpp
- src/media_centers/kodi/v17/TvShowXmlWriterV17.cpp
- src/scrapers/tv_show/ShowMerger.cpp
- src/scrapers/tv_show/tmdb/TmdbTvShowParser.cpp
- src/tv_shows/TvShow.cpp
- src/tv_shows/TvShow.h
- src/ui/export/CsvExportDialog.cpp
- src/ui/tv_show/TvShowWidgetTvShow.cpp
- src/ui/tv_show/TvShowWidgetTvShow.h
- src/ui/tv_show/TvShowWidgetTvShow.ui
- test/integration/media_centers/testKodi_v18_show.cpp
- test/resources/show/kodi_v18_show_Game_of_Thrones.nfo
- test/resources/show/kodi_v18_show_Torchwood.nfo
- test/resources/show/kodi_v18_show_all.nfo
- test/scrapers/tmdbtv/testTmdbTvShowLoader.cpp
> [TvShow] Add "originaltitle" field

- CHANGELOG.md
- src/globals/Helper.h
- src/scrapers/tv_show/ShowMerger.cpp
- src/scrapers/tv_show/imdb/ImdbTvEpisodeParser.cpp
- src/scrapers/tv_show/imdb/ImdbTvShowParser.cpp
- src/scrapers/tv_show/thetvdb/TheTvDbShowParser.cpp
- src/tv_shows/TvShow.cpp
- src/tv_shows/TvShowEpisode.cpp
- src/tv_shows/TvShowUpdater.cpp
Advancedsettings provide a way to set mappings.  Use them for all
scrapers.
-------------------
See #1176
Tested with `advancedsettings.xml` from @ticao2
> [TvShow] Map genre/certification/studio for all scrapers

- CHANGELOG.md
- src/globals/ImageDialog.cpp
- src/media_centers/KodiVersion.cpp
- src/media_centers/KodiVersion.h
- src/scrapers/concert/tmdb/TmdbConcert.cpp
- src/scrapers/image/FanartTv.cpp
- src/scrapers/image/FanartTvMusic.cpp
- src/scrapers/image/FanartTvMusicArtists.cpp
- src/scrapers/movie/aebn/AEBN.cpp
- src/scrapers/movie/imdb/ImdbMovie.cpp
- src/scrapers/movie/tmdb/TmdbMovie.cpp
- src/scrapers/music/UniversalMusicScraper.cpp
- src/scrapers/tv_show/ShowSearchJob.cpp
- src/scrapers/tv_show/tmdb/TmdbTvShowSearchJob.cpp
- src/settings/KodiSettings.cpp
- src/settings/ScraperSettings.h
- src/tv_shows/TvShowUpdater.cpp
- src/ui/settings/KodiSettingsWidget.cpp
- src/ui/tv_show/TvShowMultiScrapeDialog.cpp
- src/ui/tv_show/TvShowSearchWidget.cpp
- Fix #1190 
- Fix #1192 
- Fix #1193
> [TVShowSearch] Remove the year from the initial search string + other smaller fixes

- CHANGELOG.md
- src/data/MediaInfoFile.cpp
> [MediaInfo] Fix duration detection

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/scraper-does-not-work.md
- CHANGELOG.md
- CMakeLists.txt
- MediaElch.plist
- Version.h
- docs/admin/release.md
- obs/MediaElch.spec
- obs/README.md
New bugfix release without any major internal changes.
---------
All changes that I have planned need proper testing (not just by me). So release a stable version before doing any major refactoring.
> [Release] Prepare release of v2.8.6

- src/concerts/ConcertModel.cpp
- src/media_centers/KodiXml.cpp
- src/media_centers/KodiXml.h
- src/media_centers/MediaCenterInterface.h
- src/movies/MovieModel.cpp
- src/music/MusicModel.cpp
- src/music/MusicModel.h
- src/tv_shows/TvShowModel.cpp
- src/tv_shows/TvShowModel.h
- src/tv_shows/TvShowProxyModel.cpp
- src/tv_shows/TvShowProxyModel.h
- src/tv_shows/model/TvShowModelItem.cpp
- src/tv_shows/model/TvShowModelItem.h
- src/tv_shows/model/TvShowRootModelItem.cpp
- src/tv_shows/model/TvShowRootModelItem.h
- src/ui/concerts/ConcertInfoWidget.cpp
- src/ui/movie_sets/SetsWidget.cpp
- src/ui/tv_show/TvShowFilesWidget.cpp
- src/ui/tv_show/TvShowWidgetEpisode.cpp
- test/integration/media_centers/testKodi_v18_movie.cpp
- test/resources/movie/kodi_v18_movie_all.nfo
After watching https://www.youtube.com/watch?v=gs4_Edwx08E I went through are models and fixed a few places where the models behaved incorrectly.
> [Models] Fix invalid row index in clear() methods

- src/concerts/ConcertModel.cpp
- src/concerts/ConcertModel.h
- src/image/ImageModel.cpp
- src/image/ImageModel.h
- src/movies/MovieModel.cpp
- src/movies/MovieModel.h
- src/movies/MovieProxyModel.cpp
- src/movies/MovieProxyModel.h
- src/ui/movies/MovieDuplicates.cpp
> [Models] Use RoleNames instead of `Qt::UserRole + N`

- CHANGELOG.md
- src/export/CsvExport.cpp
- src/export/CsvExport.h
- src/ui/export/CsvExportDialog.cpp
> [CsvExport] Add Streamdetails to export list

- CHANGELOG.md
- CMakeLists.txt
- MediaElch.pro
- src/movies/MovieModel.cpp
- src/scrapers/music/UniversalMusicScraper.cpp
- src/ui/main/CMakeLists.txt
- src/ui/main/MainWindow.cpp
- src/ui/main/MainWindow.h
- src/ui/main/QuickOpen.cpp
- src/ui/main/QuickOpen.h
- src/ui/movies/MovieFilesWidget.cpp
- src/ui/movies/MovieFilesWidget.h
- third_party/kfts/kfts_fuzzy_match.h
Similar to https://kate-editor.org/post/2021/2021-01-10-kate-quick-open/
> [MainWindow] Add fuzzy quick open dialog for movies

- .ci/win/package_windows.sh
> [CI] Also package Qt's translation files for Windows + fix latest nigthly

- CHANGELOG.md
- src/media_centers/kodi/TvShowXmlWriter.cpp
- src/movies/CMakeLists.txt
- src/scrapers/tmdb/TmdbApi.cpp
- src/scrapers/tv_show/tmdb/TmdbTvEpisodeParser.cpp
- src/tv_shows/TvDbId.cpp
- src/tv_shows/TvDbId.h
- test/integration/media_centers/testKodi_v18_show.cpp
- test/integration/resource_dir.cpp
- test/resources/show/kodi_v18_show_Game_of_Thrones.nfo
- test/resources/show/kodi_v18_show_Game_of_Thrones_TvDb_episode_guide.nfo
- test/resources/show/kodi_v18_show_Torchwood.nfo
- test/resources/show/kodi_v18_show_all.nfo
- test/resources/show/kodi_v18_show_empty.nfo
- test/unit/tv_shows/testTvDbId.cpp
> [TvShow] Use TMDb for episodeguide and TvDb only as fallback 

- src/imports/DownloadFileSearcher.cpp
- src/movies/file_searcher/MovieFileSearcher.cpp
- src/scrapers/movie/aebn/AEBN.cpp
- src/scrapers/movie/tmdb/TmdbMovie.cpp
- src/scrapers/movie/videobuster/VideoBuster.cpp
- src/scrapers/music/AllMusic.cpp
- src/scrapers/music/Discogs.cpp
- src/scrapers/music/TvTunes.cpp
- src/scrapers/music/UniversalMusicScraper.cpp
- src/scrapers/tv_show/imdb/ImdbTvEpisodeParser.cpp
> [Project] Use QRegularExpression instead of QRegEx in more places

- src/data/StreamDetails.cpp
- src/data/StreamDetails.h
- src/globals/Globals.h
- src/movies/MovieModel.h
- src/renamer/ConcertRenamer.cpp
- src/renamer/EpisodeRenamer.cpp
- src/renamer/MovieRenamer.cpp
- src/renamer/RenamerPlaceholders.ui
- src/settings/Settings.h
- src/ui/main/AboutDialog.cpp
- src/ui/main/AboutDialog.h
- src/ui/main/AboutDialog.ui
- src/ui/main/MainWindow.cpp
- src/ui/main/MainWindow.h
- src/ui/movies/MovieFilesWidget.cpp
- src/ui/small_widgets/ActorsWidget.h
This PR contains a few commits that fix some smaller bugs or implement feature requests. It's my "development" branch.
- fIx https://github.com/Komet/MediaElch/issues/423
- fix https://github.com/Komet/MediaElch/issues/745
I'm not a big fan of it, but I'm currently using "-" as a separator between multiple audio/subtitle languages
> [Dev] Implement smaller feature requests

- CMakeLists.txt
- MediaElch.pro
- data/desktop/com.kvibes.MediaElch.metainfo.xml
Specification according to
https://www.freedesktop.org/software/appstream/docs/
> [Desktop] Add com.kvibes.MediaElch.metainfo.xml

- CHANGELOG.md
- src/ui/default.css
- src/ui/export/CsvExportDialog.ui
- src/ui/main/MainWindow.cpp
- src/ui/main/Navbar.cpp
- src/ui/main/Navbar.h
- src/ui/main/Navbar.ui
Make it possible to open the now stable CSV exporter from the UI.
> [Export] Add dropdown menu for CSV/HTML export

- src/tv_shows/TvShow.cpp
- src/tv_shows/TvShow.h
- src/ui/movies/CertificationWidget.cpp
- src/ui/movies/MovieWidget.cpp
- src/ui/tv_show/TvShowWidgetEpisode.cpp
- src/ui/tv_show/TvShowWidgetTvShow.cpp
> [TvShowWidget] Also list all TV show's certifications in combobox

- .ci/win/dll_list.txt
- src/movies/MovieModel.cpp
- src/ui/movies/MovieFilesWidget.cpp
- src/ui/settings/SettingsWindow.ui
> [CI] Package Qt5Svg.dll for Windows

- CHANGELOG.md
- src/settings/Settings.cpp
- src/ui/movie_sets/SetsWidget.cpp
- src/ui/settings/MovieSettingsWidget.cpp
> [MovieSets] Fix use-after-free when reloading movies

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/scraper-does-not-work.md
- CHANGELOG.md
- CMakeLists.txt
- MediaElch.plist
- Version.h
- docs/admin/release.md
- obs/MediaElch.spec
- obs/README.md
There are a few bug fixes that I want to have released.
> [Release] Prepare release of v2.8.10

- CHANGELOG.md
- src/music/AlbumController.cpp
- src/music/ArtistController.cpp
- src/scrapers/music/AllMusic.cpp
- src/scrapers/music/MusicBrainz.cpp
- src/scrapers/music/MusicBrainz.h
- src/scrapers/music/MusicScraper.h
- src/scrapers/music/UniversalMusicScraper.cpp
- src/scrapers/music/UniversalMusicScraper.h
- src/ui/music/MusicSearchWidget.cpp
- src/ui/music/MusicWidgetAlbum.cpp
- test/scrapers/CMakeLists.txt
- test/scrapers/universalmusicscraper/testUniversalMusicScraper.cpp
- test/scrapers/universalmusicscraper/testUniversalMusicScraperHelper.cpp
- test/scrapers/universalmusicscraper/testUniversalMusicScraperHelper.h
Fix #1313
---------
Not the nicest coding but gets the job done for now.
> [UniversalMusicScraper] Fix AllMusic scraping

- src/movies/file_searcher/MovieDirectorySearcher.cpp
- src/movies/file_searcher/MovieDirectorySearcher.h
- src/movies/file_searcher/MovieFileSearcher.cpp
- src/movies/file_searcher/MovieFileSearcher.h
- src/ui/main/FileScannerDialog.cpp
> [MovieFileSearcher] Check if aborted after processEvents() call

- MediaElch.pro
- src/scrapers/imdb/CMakeLists.txt
- src/scrapers/imdb/ImdbApi.cpp
- src/scrapers/imdb/ImdbApi.h
- src/scrapers/imdb/ImdbReferencePage.cpp
- src/scrapers/imdb/ImdbReferencePage.h
- src/scrapers/movie/imdb/ImdbMovie.cpp
- src/scrapers/movie/imdb/ImdbMovieScraper.cpp
- src/scrapers/movie/imdb/ImdbMovieScraper.h
- src/scrapers/movie/imdb/ImdbMovieSearchJob.cpp
- src/scrapers/movie/imdb/ImdbMovieSearchJob.h
- src/scrapers/tv_show/imdb/ImdbTvEpisodeParser.cpp
- src/scrapers/tv_show/imdb/ImdbTvEpisodeScrapeJob.cpp
- src/scrapers/tv_show/imdb/ImdbTvSeasonScrapeJob.cpp
- src/scrapers/tv_show/imdb/ImdbTvShowParser.cpp
- src/scrapers/tv_show/imdb/ImdbTvShowParser.h
- src/scrapers/tv_show/imdb/ImdbTvShowScrapeJob.cpp
- test/scrapers/imdbtv/testImdbTvEpisodeLoader.cpp
- test/scrapers/imdbtv/testImdbTvShowLoader.cpp
- test/scrapers/testImdbMovie.cpp
> [IMDb] Prepare scraper for next IMDb do-over

- CHANGELOG.md
- src/globals/ScraperManager.cpp
- src/scrapers/tv_show/custom/CustomEpisodeScrapeJob.cpp
- src/scrapers/tv_show/custom/CustomSeasonScrapeJob.cpp
- src/scrapers/tv_show/custom/CustomShowScrapeJob.cpp
- src/scrapers/tv_show/custom/CustomTvScraper.cpp
- src/scrapers/tv_show/custom/CustomTvScraper.h
- src/scrapers/tv_show/custom/CustomTvScraperConfig.cpp
- src/scrapers/tv_show/custom/CustomTvScraperConfig.h
- src/settings/Settings.cpp
TheTvDb will be removed in the near future.  This commit is the first
step in that direction.
> [Custom TV Scraper] Remove support for TheTvDb

- CHANGELOG.md
- src/data/Database.cpp
- src/data/Database.h
- src/settings/Settings.cpp
- src/tv_shows/TvShow.cpp
- src/tv_shows/TvShowUpdater.cpp
- src/tv_shows/TvShowUpdater.h
- src/ui/tv_show/TvShowFilesWidget.cpp
- src/ui/tv_show/TvShowSearchWidget.cpp
We will remove TheTvDb slowly.  Now, the TV show updater no longer requires TheTvDb to work.
> [TvShow] Use TMDb for TV show updater

- CHANGELOG.md
- src/scrapers/music/AllMusic.cpp
- src/scrapers/music/Discogs.cpp
- src/scrapers/music/TheAudioDb.cpp
- src/scrapers/music/UniversalMusicScraper.cpp
- test/scrapers/CMakeLists.txt
- test/scrapers/universalmusicscraper/testAllMusic.cpp
- test/scrapers/universalmusicscraper/testUniversalMusicScraper.cpp
> [AllMusic] Correctly scrape artist biography again | improve "year" checks

- src/renamer/EpisodeRenamer.cpp
- src/renamer/RenamerPlaceholders.ui
- src/tv_shows/TvShowEpisode.cpp
- src/tv_shows/TvShowEpisode.h
The placeholder holds the season name. If the season name isn't specified, it holds an empty string.
The condition is valid if the season name is an empty string.
Implements #1378
> [Renamer] Add "seasonName" placeholder and condition

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/scraper-does-not-work.md
- .github/workflows/superlinter.yml
- CHANGELOG.md
- CMakeLists.txt
- MediaElch.plist
- Version.h
- debian/changelog
- docs/admin/coverity.md
- docs/admin/release.md
- obs/MediaElch.changes
- obs/MediaElch.spec
- obs/README.md
- src/imports/MakeMkvCon.cpp
- src/imports/MakeMkvCon.h
> [Release] Prepare release of v2.8.16

- .ci/ci_utils.sh
- .ci/linux/package_linux_appimage.sh
- .ci/macOS/package_macOS.sh
- .ci/third_party_versions.sh
- .ci/win/build_windows_release.sh
- .ci/win/package_windows.sh
- cmake/warnings.cmake
> [CI] Use sha512 sums for all downloaded dependencies

- src/export/CsvExport.cpp
- src/export/CsvExport.h
- src/ui/export/CsvExportDialog.cpp
"date added" is only available if imported through NFO from Kodi, but
it may be useful for users.
The "type" is is only useful for uploads to other platforms.
----------------
For #1455
> [CSV Export] Add "date added"/"type" field for movies and TV shows

- CHANGELOG.md
- src/export/CsvExport.cpp
- src/export/CsvExport.h
- src/ui/export/CsvExportDialog.cpp
"date added" is only available if imported through NFO from Kodi,
therefore not useful.
"last modified", however", is quite useful.
------------
For  #1456
> [CSV Export] Add "last modified" field for movies; remove "date added"

- Jenkinsfile
- scripts/run_cppcheck.sh
- src/file_search/TvShowFileSearcher.cpp
- src/media/MediaInfoFile.h
- src/media_center/KodiXml.cpp
- src/model/ActorModel.cpp
- src/model/tv_show/TvShowUtils.cpp
- src/scrapers/movie/tmdb/TmdbMovie.h
- src/ui/concerts/ConcertWidget.cpp
- src/ui/main/Update.cpp
- src/ui/media_center/KodiSync.cpp
- src/ui/movies/MovieWidget.cpp
- src/ui/tv_show/TvShowWidgetEpisode.cpp
> fix(cppcheck): Fix cppcheck errors and warnings: possible nullptr deref

- .ci/README.md
- .ci/macOS/build_macOS_release_Qt5.sh
- .ci/macOS/build_macOS_release_Qt6.sh
- .ci/macOS/package_macOS_Qt5.sh
- .ci/macOS/package_macOS_Qt6.sh
> ci(macOS): Adapt build script to build Qt5 and Qt6

- CHANGELOG.md
- src/scrapers/tv_show/imdb/ImdbTvShowParser.cpp
- test/resources/scrapers/ade/DVD-Magic-Mike-1745335.ref.txt
- test/resources/scrapers/ade/VOD-50-Shades-1670507.ref.txt
- test/resources/scrapers/aebn/M-Is-For-Mischief-159236.ref.txt
- test/resources/scrapers/imdb/Godfather_tt0068646.ref.txt
- test/resources/scrapers/imdb/Pacific_Rim_tt1663662.ref.txt
- test/resources/scrapers/imdb/The_Shawshank_Redemption_tt0111161.ref.txt
- test/resources/scrapers/imdbtv/Scrubs-tt0285403.ref.txt
- test/resources/scrapers/imdbtv/Sherlock-tt0285403.ref.txt
- test/resources/scrapers/imdbtv/The-Simpsons-S12E19-minimal-details.ref.txt
- test/resources/scrapers/imdbtv/The-Simpsons-S12E19-tt0701133-all-details.ref.txt
- test/resources/scrapers/imdbtv/The-Simpsons-S12E19-tt0701133-minimal-details.ref.txt
- test/resources/scrapers/imdbtv/The-Simpsons-tt0096697-minimal-details.ref.txt
- test/resources/scrapers/tmdb/Finding_Dory_tmdb127380.ref.txt
- test/resources/scrapers/tmdb/Finding_Dory_tt2277860.ref.txt
- test/resources/scrapers/tmdb_concert/Katy_Perry_MTV_Unplugged_tmdb167366.ref.txt
- test/resources/scrapers/tmdb_concert/Rammstein_in_Amerika_tmdb361631.ref.txt
- test/resources/scrapers/tmdbtv/Scrubs-tmdb4556-all-details-DE.ref.txt
- test/resources/scrapers/tmdbtv/Scrubs-tmdb4556-all-details.ref.txt
- test/resources/scrapers/tmdbtv/Scrubs-tmdb4556-minimal-details-DE.ref.txt
- test/resources/scrapers/tmdbtv/Stargate-SG-1-tmdb4629.ref.txt
- test/resources/scrapers/tmdbtv/The-Simpsons-tmdb456-minimal-details.ref.txt
IMDb runtimes were not properly loaded for TV shows.
> fix(scrapers): Load IMDb TV runtime for movies and TV shows again

- CHANGELOG.md
- src/scrapers/movie/tmdb/TmdbMovie.cpp
- src/ui/main/AboutDialog.cpp
- src/ui/main/AboutDialog.ui
If there were parse errors in the JSON response, still remove "Infos"
from "downloads left" queue, because otherwise, we get stuck
Fixes #1505
> fix(TmdbMovie): Fix scraper getting stuck for multi-movie scraping

- CHANGELOG.md
- src/scrapers/imdb/ImdbApi.cpp
- src/scrapers/movie/imdb/ImdbMovieSearchJob.cpp
- src/scrapers/tv_show/imdb/ImdbTvShowSearchJob.cpp
- test/helpers/normalize.cpp
- test/integration/main.cpp
- test/resources/scrapers/ade/DVD-Magic-Mike-1745335.ref.txt
- test/resources/scrapers/ade/VOD-50-Shades-1670507.ref.txt
- test/resources/scrapers/imdb/Godfather_tt0068646.ref.txt
- test/resources/scrapers/imdb/Pacific_Rim_tt1663662.ref.txt
- test/resources/scrapers/imdb/The_Shawshank_Redemption_tt0111161.ref.txt
- test/resources/scrapers/imdbtv/Scrubs-tt0285403.ref.txt
- test/resources/scrapers/imdbtv/Sherlock-tt0285403.ref.txt
- test/resources/scrapers/imdbtv/The-Simpsons-tt0096697-minimal-details.ref.txt
- test/resources/scrapers/tmdbtv/Scrubs-tmdb4556-all-details-DE.ref.txt
- test/resources/scrapers/tmdbtv/Scrubs-tmdb4556-all-details.ref.txt
- test/resources/scrapers/tmdbtv/Scrubs-tmdb4556-minimal-details-DE.ref.txt
- test/resources/scrapers/tmdbtv/The-Simpsons-tmdb456-minimal-details.ref.txt
- test/resources/scrapers/tvmaze/The-Simpsons-all-details.ref.txt
- test/resources/scrapers/tvmaze/The-Simpsons-minimal-details.ref.txt
- test/scrapers/imdbtv/testImdbTvShowSearch.cpp
- test/scrapers/main.cpp
The IMDb search page was changed again.  Use the "more stable" advanced
search page.
> fix(IMDb): Fix movie/tv show search for IMDb

- src/ui/small_widgets/TvShowTreeView.cpp
Follow up to 429185d8d60ef5d88bbeaa113530ad57b3205cf6
Fix #1525
> fix(TvShowTreeView): Fix build issue on non-mac after recent refactoring

- .ci/README.md
- .ci/jenkins/CoverityScan.groovy
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/scraper-does-not-work.md
- CHANGELOG.md
- CMakeLists.txt
- MediaElch.plist
- Version.h
- debian/changelog
- docs/admin/release.md
- obs/MediaElch.changes
- obs/README.md
@Komet What new name should the next minor version get? Since I'm not a big Star Trek watcher, I googled and propose Benzar. :)
> release: Prepare release of v2.10.0

- src/ui/tv_show/TvShowMultiScrapeDialog.cpp
> fix: Remove unsupported TheTvDb from TV multi scraper dropdown menu

- CHANGELOG.md
- src/data/concert/ConcertController.cpp
- src/data/movie/MovieController.cpp
- src/data/tv_show/TvShow.cpp
- src/data/tv_show/TvShowEpisode.cpp
- src/media_center/KodiXml.cpp
- src/media_center/kodi/AlbumXmlReader.cpp
- src/media_center/kodi/AlbumXmlReader.h
- src/media_center/kodi/ArtistXmlReader.cpp
- src/media_center/kodi/ArtistXmlReader.h
- src/media_center/kodi/EpisodeXmlReader.cpp
- src/media_center/kodi/EpisodeXmlReader.h
- src/media_center/kodi/MovieXmlReader.cpp
- src/media_center/kodi/MovieXmlReader.h
- src/media_center/kodi/TvShowXmlReader.cpp
- src/media_center/kodi/TvShowXmlReader.h
- test/integration/media_center/testKodi_v18_episode.cpp
- test/integration/media_center/testKodi_v18_movie.cpp
- test/integration/media_center/testKodi_v18_music_album.cpp
- test/integration/media_center/testKodi_v18_music_artist.cpp
- test/integration/media_center/testKodi_v18_show.cpp
- test/integration/media_center/testKodi_v20_show.cpp
> fix(file searcher): Don't ignore movies if their NFO can't be parsed

- CHANGELOG.md
- src/scrapers/movie/custom/CustomMovieScraper.cpp
- src/ui/settings/ScraperSettingsWidget.cpp
> feat(CustomMovieScraper): Allow scraping of tags

- CHANGELOG.md
- src/data/tv_show/TvShow.cpp
- src/scrapers/tv_show/imdb/ImdbTvShowSearchJob.cpp
- test/scrapers/imdbtv/testImdbTvShowSearch.cpp
> feat(IMDb TV): Allow searching by IMDb ID

- src/scrapers/movie/imdb/ImdbMovieSearchJob.cpp
- test/scrapers/testImdbMovie.cpp
> fix(IMDb): Also scrape year of movies for search result list

- docs/concepts/README.md
- docs/concepts/renamer.md
> doc(Concepts): Write about a new renamer concept

- data/i18n/MediaElch_es_ES.ts
- src/renamer/MovieRenamer.cpp
This was forgotten in #1021 / 8de9fde1ce69e464d701ecabb6a16f7fabcfec33
----
Fix  #1611
> fix(Renamer): Also replace `<director>` in movie folders, not just files

- CHANGELOG.md
- src/data/tv_show/TvShow.cpp
- src/data/tv_show/TvShow.h
- src/ui/tv_show/TvShowWidgetTvShow.cpp
> fix(TV Show): Fix revert button on TV shows

- src/ui/movies/MovieSearch.cpp
- src/ui/movies/MovieSearch.h
- src/ui/movies/MovieSearch.ui
- src/ui/movies/MovieSearchWidget.cpp
- src/ui/movies/MovieSearchWidget.h
Follow up to 4a7b08833aef71a5e1fe1ac850410203c466546a
This commit adds a "scrape" button to the movie search dialog, similar to how it is done for TV shows.
> feat(Movie Search): Add "scrape" button; don't rely on double click

- CHANGELOG.md
- src/ui/tv_show/TvShowWidgetEpisode.cpp
- src/ui/tv_show/TvShowWidgetEpisode.h
- src/ui/tv_show/TvShowWidgetEpisode.ui
> feat(UI): Show TMDB id for TV show episodes

- CHANGELOG.md
- src/ui/movies/MovieWidget.cpp
- src/ui/tv_show/TvShowWidgetEpisode.cpp
- src/ui/tv_show/TvShowWidgetEpisode.h
- src/ui/tv_show/TvShowWidgetEpisode.ui
- src/ui/tv_show/TvShowWidgetTvShow.cpp
- src/ui/tv_show/TvShowWidgetTvShow.h
- src/ui/tv_show/TvShowWidgetTvShow.ui
To open the website corresponding to the ID, click the newly added buttons.
---
Fix #1645
> feat(TV Show): Add buttons (URLs) next to TV show IDs

- CHANGELOG.md
- src/file_search/movie/MovieDirectorySearcher.cpp
See #1653
@Neinei0k Let me know if it's fine to mention you in the changelog. Didn't want to push this without asking you first. :)
(The other diffs are just `clang-format` fixes)
> chore: Update changelog to include latest "exclusion filter" fix

- CHANGELOG.md
- src/main.cpp
- src/ui/base.css
- src/ui/dark.css
- src/ui/light.css
- src/ui/settings/GlobalSettingsWidget.ui
> fix(UI): Properly color QComboBox (non editbale) for dark theme

- CHANGELOG.md
- src/network/NetworkRequest.cpp
- src/scrapers/music/AllMusic.cpp
- src/scrapers/music/AllMusic.h
- src/scrapers/music/UniversalMusicScraper.cpp
- test/resources/scrapers/universalmusicscraper/master-of-puppets.ref.txt
Follow up to #1674
Fix https://github.com/Komet/MediaElch/issues/1606
> fix(Music): Universal Music Scraper fix biography/moods scraping

- CHANGELOG.md
- src/scrapers/movie/imdb/ImdbMovieScrapeJob.cpp
- test/resources/scrapers/fernsehserien_de/Scrubs.ref.txt
- test/resources/scrapers/imdb/Finding_Dory_tt2277860.ref.txt
- test/resources/scrapers/tmdb/Finding_Dory_tmdb127380.ref.txt
- test/resources/scrapers/tmdb_concert/Katy_Perry_MTV_Unplugged_tmdb167366.ref.txt
- test/resources/scrapers/tmdbtv/Scrubs-tmdb4556-all-details-DE.ref.txt
- test/resources/scrapers/tmdbtv/Scrubs-tmdb4556-all-details.ref.txt
- test/resources/scrapers/tmdbtv/Scrubs-tmdb4556-minimal-details-DE.ref.txt
- test/resources/scrapers/tmdbtv/Stargate-SG-1-tmdb4629.ref.txt
- test/resources/scrapers/tmdbtv/The-Simpsons-S12.ref.txt
- test/resources/scrapers/tmdbtv/The-Simpsons-tmdb456-S12E19-all-details-DE.ref.txt
- test/resources/scrapers/tmdbtv/The-Simpsons-tmdb456-minimal-details.ref.txt
- test/resources/scrapers/tvmaze/The-Simpsons-all-details.ref.txt
- test/resources/scrapers/tvmaze/The-Simpsons-minimal-details.ref.txt
- test/scrapers/main.cpp
- test/scrapers/testImdbMovie.cpp
> fix(IMDb): Fix loading of _all_ tags of a movie

- .ci/linux/check_linux_dependencies.sh
- .ci/linux/package_linux_launchpad.sh
> ci: Update debian packaging script: use CMake

- CHANGELOG.md
- src/scrapers/tv_show/imdb/ImdbTvEpisodeParser.cpp
- test/resources/scrapers/imdbtv/Black-Mirror-S05.ref.txt
- test/resources/scrapers/imdbtv/Buffy-S01E00-minimal-details.ref.txt
- test/resources/scrapers/imdbtv/Buffy-S01E01-minimal-details.ref.txt
- test/resources/scrapers/imdbtv/The-Simpsons-S12E19-minimal-details.ref.txt
- test/resources/scrapers/imdbtv/The-Simpsons-S12E19-tt0701133-all-details.ref.txt
- test/resources/scrapers/imdbtv/The-Simpsons-S12E19-tt0701133-minimal-details.ref.txt
> fix(IMDb): Fix scraping of episode's overviews

- CHANGELOG.md
- src/ui/movies/MovieWidget.cpp
- src/ui/movies/MovieWidget.ui
- src/ui/tv_show/TvShowWidgetEpisode.ui
- src/ui/tv_show/TvShowWidgetTvShow.ui
> fix(UI): Use full date for movie's release-date, not just its year

- CHANGELOG.md
- src/scrapers/tv_show/imdb/ImdbTvEpisodeParser.cpp
- test/resources/scrapers/imdbtv/All-in-the-Family-S01E01-tt0509891-minimal-details.ref.txt
- test/resources/scrapers/imdbtv/Black-Mirror-S05.ref.txt
- test/scrapers/imdbtv/testImdbTvEpisodeLoader.cpp
Episodes of "All in the Family" were not properly scraped.
Fix #1751
> fix(IMDB): Adapt episode scraper to new episode page for old TV shows

- .ci/jenkins/NightlyDeploymentMacOsQt5.groovy
- .ci/jenkins/NightlyDeploymentMacOsQt6.groovy
I finally have a macOS Jenkins agent.
> ci(Jenkins): Add nightly deployment scripts for macOS

- CHANGELOG.md
- src/scrapers/imdb/ImdbReferencePage.cpp
- src/scrapers/tv_show/imdb/ImdbTvShowParser.cpp
- test/resources/scrapers/imdbtv/Maters-Tall-Tales-tt1384816.ref.txt
- test/scrapers/imdbtv/testImdbTvShowLoader.cpp
> fix(IMDb TV): Fix missing decoding of HTML entities in show titles

- CHANGELOG.md
- src/data/concert/Concert.cpp
- src/data/concert/Concert.h
- src/data/movie/Movie.cpp
- src/data/movie/Movie.h
- src/data/tv_show/TvShowEpisode.cpp
- src/export/CsvExport.cpp
- src/export/SimpleEngine.cpp
- src/media_center/kodi/ConcertXmlReader.cpp
- src/media_center/kodi/ConcertXmlWriter.cpp
- src/media_center/kodi/MovieXmlWriter.cpp
- src/renamer/ConcertRenamer.cpp
- src/scrapers/movie/imdb/ImdbMovieScrapeJob.cpp
- src/settings/AdvancedSettings.cpp
- src/ui/concerts/ConcertFilesWidget.cpp
- src/ui/concerts/ConcertInfoWidget.cpp
- src/ui/import/ImportDialog.cpp
- src/ui/movies/MovieFilesWidget.cpp
- src/ui/movies/MovieWidget.cpp
- test/helpers/reference_file.cpp
- test/integration/media_center/testKodi_v18_concert.cpp
- test/resources/concert/kodi_v18_Rammstein_in_Amerika_2015.nfo
- test/resources/scrapers/tmdb_concert/Katy_Perry_MTV_Unplugged_tmdb167366.ref.txt
- test/resources/scrapers/tmdb_concert/Rammstein_in_Amerika_tmdb361631.ref.txt
- test/resources/scrapers/tmdbtv/Stargate-SG-1-tmdb4629.ref.txt
- test/resources/scrapers/tmdbtv/The-Simpsons-tmdb456-minimal-details.ref.txt
> feat(Concerts): Support multiple `<artist>` tags

- src/media_center/kodi/MovieXmlReader.cpp
- src/ui/movies/MovieWidget.cpp
- src/ui/movies/MovieWidget.h
- src/ui/movies/MovieWidget.ui
- src/ui/small_widgets/TagCloud.cpp
- src/ui/small_widgets/TagCloud.h
> feat(movies): Show TV show links as tag cloud

- CHANGELOG.md
- data/MediaElch.qrc
- data/README.md
- data/icons/actions/32/media-playback-start.svg
- src/model/MovieModel.cpp
- src/ui/movies/MovieWidget.cpp
- src/ui/movies/MovieWidget.h
- src/ui/movies/MovieWidget.ui
> feat(UI): Add play button to movie widget

- CHANGELOG.md
- src/scrapers/tv_show/tvmaze/TvMaze.cpp
- test/resources/scrapers/tvmaze/The-Three-Stooges-all-details.ref.txt
- test/scrapers/tvmaze/testTvMazeShowScrapeJob.cpp
> fix(TVMaze): Store scraped premiered/first-aired date of TV shows

- CHANGELOG.md
- src/ui/concerts/ConcertWidget.cpp
- src/ui/concerts/ConcertWidget.h
- src/ui/concerts/ConcertWidget.ui
- src/ui/movies/MovieWidget.cpp
- src/ui/tv_show/TvShowWidgetEpisode.cpp
- src/ui/tv_show/TvShowWidgetEpisode.h
- src/ui/tv_show/TvShowWidgetEpisode.ui
> feat(UI): Add play button to episode and concert widget

- MediaElch.pro
- scripts/list_qmake_sources.sh
Let's semi-automate the file generation.
> build: Add script to create source lists for QMake file

- MediaElch.pro
- src/scrapers/image/CMakeLists.txt
- src/scrapers/image/TheTvDbImages.cpp
- src/scrapers/image/TheTvDbImagesConfiguration.cpp
- src/scrapers/image/TheTvDbImagesConfiguration.h
- src/ui/image/ImageDialog.cpp
- src/ui/scrapers/CMakeLists.txt
- src/ui/scrapers/ScraperManager.cpp
- src/ui/scrapers/image/TheTvDbImagesConfigurationView.cpp
- src/ui/scrapers/image/TheTvDbImagesConfigurationView.h
Follow up to 68ea08ddf2e0d4d7bddc8a4ca0a12f0be79b9ff1
Fix #1786
---
> fix(UI): Fix TheTvDbImages language configuration

- CHANGELOG.md
- src/data/movie/MovieController.cpp
- src/data/tv_show/TvShowEpisode.cpp
- src/data/tv_show/TvShowEpisode.h
- src/scrapers/tv_show/ShowMerger.cpp
- src/ui/tv_show/TvShowMultiScrapeDialog.cpp
- src/ui/tv_show/TvShowWidgetEpisode.cpp
- src/ui/tv_show/TvShowWidgetEpisode.h
- src/ui/tv_show/TvShowWidgetTvShow.cpp
- src/ui/tv_show/TvShowWidgetTvShow.h
For #1486
Fix #1792
Fix #1784
With this change, actor images will be downloaded for episodes if requested.
> feat(TV): Download episode actor images when requested

- .ci/docker/build-opensuse.sh
- .ci/linux/build_linux_release.sh
- .ci/linux/build_linux_release_in_docker.sh
- .ci/linux/package_linux_appimage_in_docker.sh
- .ci/macOS/build_macOS_release_Qt5.sh
- .ci/macOS/build_macOS_release_Qt6.sh
- .ci/win/build_windows_release.sh
- scripts/library/tvshows_en/Fullmetal_Alchemist_Brotherhood/Season_01.txt
- src/model/MovieModel.cpp
In 516c8a50a84f50c7b8f8565366b9ff2d417fe79d, we changed `onMovieChanged()`
to emit `dataChanged()` for all columns.  That, however, turned out to
be an issue! A performance problem appeared in the AppImage, which uses
Qt5.
According to answers in https://stackoverflow.com/q/53139727/1603627,
Qt uses a quick-path if both "top left" and "bottom right" index are
the same.  If it isn't it may lead to re-rendering of the whole widget.
Fix #1788
> fix(AppImage): Add workaround for performance bug in Qt

- CHANGELOG.md
- src/scrapers/movie/adultdvdempire/AdultDvdEmpireApi.cpp
- src/scrapers/movie/adultdvdempire/AdultDvdEmpireApi.h
- src/scrapers/movie/hotmovies/HotMoviesApi.cpp
- src/scrapers/movie/hotmovies/HotMoviesApi.h
- test/resources/scrapers/ade/DVD-Magic-Mike-1745335.ref.txt
- test/resources/scrapers/hot-movies/Magic-Mike-292788.ref.txt
> fix: Fix search of ADE and HotmMvies

- CHANGELOG.md
- src/scrapers/tv_show/imdb/ImdbTvEpisodeParser.cpp
- test/resources/scrapers/fernsehserien_de/Game-of-Thrones.ref.txt
- test/resources/scrapers/fernsehserien_de/Scrubs.ref.txt
- test/resources/scrapers/imdb/Welcome_Back_tt3159708.ref.txt
- test/resources/scrapers/imdbtv/All-in-the-Family-S01E01-tt0509891-minimal-details.ref.txt
- test/resources/scrapers/imdbtv/Buffy-S01E00-minimal-details.ref.txt
- test/resources/scrapers/imdbtv/Buffy-S01E01-minimal-details.ref.txt
- test/resources/scrapers/imdbtv/Maters-Tall-Tales-tt1384816.ref.txt
- test/resources/scrapers/imdbtv/The-Simpsons-S12E19-minimal-details.ref.txt
- test/resources/scrapers/imdbtv/The-Simpsons-S12E19-tt0701133-all-details.ref.txt
- test/resources/scrapers/imdbtv/The-Simpsons-S12E19-tt0701133-minimal-details.ref.txt
- test/resources/scrapers/tmdbtv/Scrubs-tmdb4556-all-details-DE.ref.txt
- test/resources/scrapers/tmdbtv/Scrubs-tmdb4556-all-details.ref.txt
- test/resources/scrapers/tmdbtv/Scrubs-tmdb4556-minimal-details-DE.ref.txt
- test/resources/scrapers/tmdbtv/Stargate-SG-1-tmdb4629.ref.txt
- test/resources/scrapers/tmdbtv/The-Simpsons-tmdb456-S12E19-all-details-DE.ref.txt
- test/resources/scrapers/tmdbtv/The-Simpsons-tmdb456-S12E19-all-details.ref.txt
- test/resources/scrapers/tmdbtv/The-Simpsons-tmdb456-S12E19-minimal-details-DE.ref.txt
- test/resources/scrapers/tmdbtv/The-Simpsons-tmdb456-S12E19-minimal-details.ref.txt
- test/resources/scrapers/tmdbtv/The-Simpsons-tmdb456-minimal-details.ref.txt
- test/resources/scrapers/tvmaze/The-Simpsons-S12E19-all-details.ref.txt
- test/resources/scrapers/tvmaze/The-Simpsons-S12E19-minimal-details.ref.txt
- test/resources/scrapers/tvmaze/The-Simpsons-all-details.ref.txt
- test/resources/scrapers/tvmaze/The-Simpsons-minimal-details.ref.txt
- test/resources/scrapers/tvmaze/The-Simpsons-tvmaze5264-all-details.ref.txt
- test/scrapers/tmdbtv/testTmdbTvShowLoader.cpp
> fix(IMDb TV): Fix directors/writer scraping

- src/globals/Helper.cpp
> feat: Loosen 2160p detection to support letterbox

- CHANGELOG.md
- src/scrapers/tv_show/tvmaze/TvMaze.cpp
- src/scrapers/tv_show/tvmaze/TvMazeApi.cpp
- src/scrapers/tv_show/tvmaze/TvMazeEpisodeParser.cpp
- test/resources/scrapers/ade/DVD-Magic-Mike-1745335.ref.txt
- test/resources/scrapers/ade/VOD-50-Shades-1670507.ref.txt
- test/resources/scrapers/discogs/metallica-details-18839.ref.txt
- test/resources/scrapers/discogs/rammstein-details-11771.ref.txt
- test/resources/scrapers/fernsehserien_de/Scrubs.ref.txt
- test/resources/scrapers/hot-movies/M-Is-For-Mischief-214343.ref.txt
- test/resources/scrapers/hot-movies/Magic-Mike-292788.ref.txt
- test/resources/scrapers/imdb/Finding_Dory_tt2277860.ref.txt
- test/resources/scrapers/imdb/Godfather_tt0068646.ref.txt
- test/resources/scrapers/imdb/Pacific_Rim_tt1663662.ref.txt
- test/resources/scrapers/imdb/The_Shawshank_Redemption_tt0111161.ref.txt
- test/resources/scrapers/imdb/Welcome_Back_tt3159708.ref.txt
- test/resources/scrapers/tmdb/Finding_Dory_tmdb127380.ref.txt
- test/resources/scrapers/tmdb/Finding_Dory_tt2277860.ref.txt
- test/resources/scrapers/tmdb/The_Rescuers_de-DE_tmdb11319.ref.txt
- test/resources/scrapers/tmdbtv/Stargate-SG-1-tmdb4629.ref.txt
- test/resources/scrapers/tmdbtv/The-Simpsons-S12.ref.txt
- test/resources/scrapers/tmdbtv/The-Simpsons-tmdb456-minimal-details.ref.txt
- test/resources/scrapers/tvmaze/The-Simpsons-all-details.ref.txt
- test/resources/scrapers/tvmaze/The-Simpsons-minimal-details.ref.txt
- test/resources/scrapers/tvmaze/The-Simpsons-tvmaze5264-all-details.ref.txt
- test/resources/scrapers/universalmusicscraper/metallica.ref.txt
- test/resources/scrapers/video-buster/Findet-Dorie-183469.ref.txt
> feat(TVMaze): Add loading of guest cast (actors)

- MediaElch.pro
- src/scrapers/movie/adultdvdempire/AdultDvdEmpire.cpp
- src/scrapers/movie/adultdvdempire/AdultDvdEmpire.h
- src/scrapers/movie/adultdvdempire/AdultDvdEmpireApi.cpp
- src/scrapers/movie/adultdvdempire/AdultDvdEmpireConfiguration.cpp
- src/scrapers/movie/adultdvdempire/AdultDvdEmpireConfiguration.h
- src/scrapers/movie/adultdvdempire/AdultDvdEmpireScrapeJob.cpp
- src/scrapers/movie/adultdvdempire/AdultDvdEmpireScrapeJob.h
- src/scrapers/movie/adultdvdempire/CMakeLists.txt
- src/ui/scrapers/CMakeLists.txt
- src/ui/scrapers/ScraperManager.cpp
- src/ui/scrapers/movie/AdultDvdEmpireConfigurationView.cpp
- src/ui/scrapers/movie/AdultDvdEmpireConfigurationView.h
- test/scrapers/testAdultDvdEmpire.cpp
For https://github.com/Komet/MediaElch/issues/1862
> feat(ADE): Make "back-cover as fanart" configurable

- CHANGELOG.md
- cmake/CatchAddTests.cmake
- cmake/sanitize-helpers.cmake
- debian/changelog
- docs/admin/release.md
- src/file_search/MovieFilesOrganizer.cpp
- src/import/MyFile.cpp
- src/main.cpp
- src/media/NameFormatter.h
- src/media_center/KodiXml.cpp
- src/scrapers/tv_show/imdb/ImdbTvEpisodeParser.cpp
- src/settings/Settings.cpp
- src/ui/concerts/ConcertInfoWidget.cpp
- src/ui/export/csv_export/CsvExportDialog.cpp
- src/ui/main/MyIconFont.cpp
- src/ui/main/MyIconFont.h
- src/ui/main/QuickOpen.cpp
- src/ui/settings/MovieSettingsWidget.ui
- src/ui/small_widgets/LanguageCombo.h
- test/unit/globals/testVersionInfo.cpp
- test/unit/renamer/testRenamer.cpp
- test/unit/tv_shows/testTvDbId.cpp
Assortment of typo fixes. Some of them are user-facing. Some doxygen. Others are source comments.
> chore: fix typos

- CHANGELOG.md
- src/media/MediaInfoFile.cpp
> fix: HDR10 detection for media files
